### ISSUE TITLE
这个不是BUG，是个咨询

### ISSUE THREAD

**Issue by tulongchao** [alibaba/atlas#109]
问一下，这个更新是否支持经过平台加固的包。如360加固，应用宝加固，类似这样的场景你们测试过吗

**Comment by hwjump** [comment]
我们没有测试过 360加固 和应用宝加固。我们测试过阿里自己的加固。  欢迎同学测试atlas对这两种加固的兼容情况。并反馈给我们。感谢

**Comment by hwjump** [comment]
另外你还可以参照 #40
