### ISSUE TITLE
执行buildTpatch.sh时报错

### ISSUE THREAD

**Issue by kevinTutu** [alibaba/atlas#11]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':prepareDebugAP'.
> Could not resolve all dependencies for configuration 'detachedConfiguration1'.
   > Could not find com.taobao.android.atlasdemo:AP-debug:1.0.0.
     Searched in the following locations:
         file:/Users/wangzihang/android_sdk/android-sdk/extras/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.pom
         file:/Users/wangzihang/android_sdk/android-sdk/extras/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.ap
         file:/Users/wangzihang/android_sdk/android-sdk/extras/google/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.pom
         file:/Users/wangzihang/android_sdk/android-sdk/extras/google/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.ap
         file:/Users/wangzihang/android_sdk/android-sdk/extras/android/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.pom
         file:/Users/wangzihang/android_sdk/android-sdk/extras/android/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.ap
         file:/Users/wangzihang/.m2/repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.pom
         file:/Users/wangzihang/.m2/repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.ap
         https://jcenter.bintray.com/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.pom
         https://jcenter.bintray.com/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.ap
     Required by:
         com.taobao.android.atlasdemo:app:1.0.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by jiawulu** [comment]
patch 是通过对比基线apk 和 当前apk 对比出来的。 你的问题是基线包不存在。

1. 是否执行过 buildApk.sh
2. 如果是看下 buildApk 的构建日志，看下是不是有部署到本地的仓库里
3. 还有问题贴下日志

**Comment by kevinTutu** [comment]
当执行过buildApk.sh后不再报错，谢谢！
     再请教一个问题，在（3）上传tpatch时，日志打印buildTpatch.sh中无adb命令：

       ./buildTpatch.sh: line 14: adb: command not found
       ./buildTpatch.sh: line 15: adb: command not found

**Comment by jiawulu** [comment]
配置下环境变量  到 PATH 里

adb 在 android-sdk 的 platform-tools  目录下
