### ISSUE TITLE
动态部署无法生成apk

### ISSUE THREAD

**Issue by zhuangdaoyuan** [alibaba/atlas#114]
使用疑问

**Comment by zhuangdaoyuan** [comment]
安装tpatch步骤：
1。执行命令：gradlew clean assembleDebug publish能够生成apk,文档有句话(生成apk同时将跟apk同目录的ap文件发布到仓库)这个仓库在哪里？如何知道是否已经发布到仓库？
2.修改modul内容后，修改版本。使用命令：gradlew clean assembleDebug -DapVersion=apVersion -DversionName=newVersion
这个时候会构建失败。
Could not find com.taobao.android.atlasdemo:AP-debug:apVersion

**Comment by zhuangdaoyuan** [comment]
![qq 20170418142647](https://cloud.githubusercontent.com/assets/11583318/25117111/1943b41c-2443-11e7-98e8-932520ed3f3b.png)

**Comment by hwjump** [comment]
仓库要你自己配置的  或者是你自己mavenlocal 或者你其他外部maven仓库。  
动态部署包是需要ap的，ap就是基线包的所有内容。用于生成动态部署diff包用。你log看是没有发布ap成功。请看一下自己的maven配置

**Comment by huscarter** [comment]
如果运行gradlew clean assembleDebug publish成功的话，有可能是baseApDependency值写错了，比如我自己项目的group为com.abc，那么就是baseApDependency "com.abc:AP-debug:${apVersion}@ap"
