### ISSUE TITLE
Demo 远程组件如果需要更新要怎么处理，先要uninstallBundle 吗？

### ISSUE THREAD

**Issue by chenhui3014** [alibaba/atlas#117]
前提：远程组件已经加载，如果要更新远程组件是要先调用uninstallBundle方法，还是其他方式可以实现

**Comment by SilverBoyMax** [comment]
同问

**Comment by hwjump** [comment]
更新远程组件，和更新本地bundle一样，要重新打出动态部署包，然后发到远端。  atlas-core会自动按需加载bundle。如果远程bundle已经在本地安装了，那会做merge，如果没有安装，那会跳过，重新到远端拉新的远程组件。

**Comment by chenlide** [comment]
如果我远程bundle更新，可以跟本地bundle一样的更新方法。但如果我远程的bundle改动太大，想直接让用户装新的远程so，又不更新宿主，这时怎么处理
