### ISSUE TITLE
buildTool 24.0.0以后使用Multidex无法生成manifest_keep.txt文件

### ISSUE THREAD

**Issue by hluguoj** [alibaba/atlas#118]
问题场景：
    buildToolsVersion "24.0.2"
    multiDexEnabled true
atlas版本是2.2
执行打包抛出build/intermediates/multi-dex/debug/manifest_keep.txt文件不存在
原因：在buildTool 24.0.0以后manifest_keep.txt文件的生成是通过在aapt命令中加入
-D manifestKeepListProguardFile 参数来生成而不是通过创建CreateManifestKeepList Task来生成。
而atlas自己修改了aapt，没有升级，导致了不支持 -D manifestKeepListProguardFile 参数，最终无法生成manifest_keep.txt文件。
源码：
// ----------
            // Create a task to collect the list of manifest entry points which are
            // needed in the primary dex.
            // This is not needed for AAPT >= AaptV1.VERSION_FOR_MAIN_DEX_LIST,
            // where the '-D manifestKeepListProguardFile' option is used instead.
            AndroidTask<CreateManifestKeepList> manifestKeepListTask = null;
            if (!useAaptToGenerateLegacyMultidexMainDexProguardRules(variantScope)) {
                manifestKeepListTask = androidTasks.create(tasks,
                        new CreateManifestKeepList.ConfigAction(variantScope));
                manifestKeepListTask.dependsOn(tasks,
                        variantData.getOutputs().get(0).getScope().getManifestProcessorTask());
                variantScope.addColdSwapBuildTask(manifestKeepListTask);
            }

解决方案（个人）：
    重新基于高版本的aapt编译一个新的aapt替换atals里面的aapt

**Comment by jiqimaogou** [comment]
现在的aapt有这个选项，请问一下你插件用的是什么版本的？

**Comment by jiqimaogou** [comment]
因为2.2的aapt我们没有这个选项，可以换成2.3的试一下
