### ISSUE TITLE
运行FirstBundle报错

### ISSUE THREAD

**Issue by Whg8908** [alibaba/atlas#12]
Error:Execution failed for task ':bundleDebug'.
> java.lang.NullPointerException (no error message)

**Comment by jiawulu** [comment]
add --stacktrace 

异常堆栈贴下

**Comment by Whg8908** [comment]
Information:Gradle tasks [clean, :generateDebugSources, :mockableAndroidJar, :prepareDebugUnitTestDependencies, :generateDebugAndroidTestSources]
Error:Execution failed for task ':bundleDebug'.
> java.lang.NullPointerException (no error message)

**Comment by jiawulu** [comment]
你的构建命令是什么？

是./gradlew assembleDebug --stacktrace 吗？

**Comment by Whg8908** [comment]
就是直接导入项目就报这个错啊

**Comment by jiawulu** [comment]
操作系统？win / mac / linux
命令行直接构建是否报错？
jdk 版本 ？ android studio 版本？

**Comment by Whg8908** [comment]
mac   jdk 1.8.0_74   android studio 2.3

**Comment by 401885064** [comment]
同问  jdk1.8.101    Android studio2.3     win7   运行一直在building。。。。

**Comment by jiawulu** [comment]
@401885064 命令行构建可以吗？ 感觉是卡在下载 gradle  了 ： 

 gradle/wrapper/gradle-wrapper.properties , 
distributionUrl=http\://services.gradle.org/distributions/gradle-2.14.1-all.zip 用的是官方的下载地址，国内比较慢

**Comment by 401885064** [comment]
@jiawulu   gradle用的是本地gradle3.3版本

**Comment by jiawulu** [comment]
@401885064  我们的插件暂时还不支持 gradle3.3 。。 gradle3.3 是 android builder 2.3.0 才开始支持的，这个还在开发适配中。 请用 gradle wrapper 吧

![image](https://cloud.githubusercontent.com/assets/748188/23885190/93a1be78-08ac-11e7-9a39-86e1e7d5fce0.png)
![image](https://cloud.githubusercontent.com/assets/748188/23885205/a4f4b644-08ac-11e7-88bd-08309134dd07.png)

**Comment by Whg8908** [comment]
![2017-03-14 12 01 26](https://cloud.githubusercontent.com/assets/16721353/23885463/297fb886-08ae-11e7-8c90-95484319b7cb.png)
![2017-03-14 12 01 42](https://cloud.githubusercontent.com/assets/16721353/23885465/2b59135a-08ae-11e7-86db-6a89332c1372.png)
![2017-03-14 12 01 51](https://cloud.githubusercontent.com/assets/16721353/23885466/2dd8e0ce-08ae-11e7-8823-103c876268de.png)
![2017-03-14 12 02 30](https://cloud.githubusercontent.com/assets/16721353/23885467/2f696526-08ae-11e7-8572-a98988b3d160.png)
用命令我不知道怎么构建,但是我gradle都是配置本地的2.14.1的,还是一直报那个错

**Comment by a3349384** [comment]
同遇到这个问题。本想使用./gradlew assembleDebug --stacktrace查看异常堆栈的，没想到用这个命令之后build居然成功了

**Comment by 317764920** [comment]
@ @a3349384 能不能把你的工程发来参考参考

**Comment by a3349384** [comment]
@317764920 就是github上那两个demo工程

**Comment by jiawulu** [comment]
FirstBunle 里的 publish 任务是执行不了的， 这里的代码需要手工修改下

`
publishing {
    publications {
        maven(MavenPublication) {
            artifact "${project.buildDir}/outputs/awb/${project.name}-release.awb"
            artifact sourcesJar
        }
    }
    repositories {
        mavenLocal()
//        maven {
//            url "url"
//            credentials {
//                username = "xxx"
//                password = "xxx"
//            }
//        }
    }
}

./gradlew clean assembleRelease publishMavenPublicationToMavenLocal
`

**Comment by mpeng5120** [comment]
$ ./gradlew clean assembleRelease publishMavenPublicationToMavenLocal

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'FirstBundle'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find dom4j:dom4j:2.0.
     Searched in the following locations:
         file:/C:/Users/Administrator/.m2/repository/dom4j/dom4j/2.0/dom4j-2.0.pom
         file:/C:/Users/Administrator/.m2/repository/dom4j/dom4j/2.0/dom4j-2.0.jar
         https://jcenter.bintray.com/dom4j/dom4j/2.0/dom4j-2.0.pom
         https://jcenter.bintray.com/dom4j/dom4j/2.0/dom4j-2.0.jar
     Required by:
         :FirstBundle:unspecified > com.taobao.android:atlasplugin:1.0.0
   > Could not find com.taobao.android:DexPatch:1.0.4-SNAPSHOT.
     Searched in the following locations:
         file:/C:/Users/Administrator/.m2/repository/com/taobao/android/DexPatch/1.0.4-SNAPSHOT/maven-metadata.xml
         file:/C:/Users/Administrator/.m2/repository/com/taobao/android/DexPatch/1.0.4-SNAPSHOT/DexPatch-1.0.4-SNAPSHOT.pom
         file:/C:/Users/Administrator/.m2/repository/com/taobao/android/DexPatch/1.0.4-SNAPSHOT/DexPatch-1.0.4-SNAPSHOT.jar
         https://jcenter.bintray.com/com/taobao/android/DexPatch/1.0.4-SNAPSHOT/maven-metadata.xml
         https://jcenter.bintray.com/com/taobao/android/DexPatch/1.0.4-SNAPSHOT/DexPatch-1.0.4-SNAPSHOT.pom
         https://jcenter.bintray.com/com/taobao/android/DexPatch/1.0.4-SNAPSHOT/DexPatch-1.0.4-SNAPSHOT.jar
     Required by:
         :FirstBundle:unspecified > com.taobao.android:atlasplugin:1.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.555 secs
 

照上面修改后用这个命令编译这是什么错？

**Comment by jiawulu** [comment]
@mpeng5120  

更新下代码 ， git pull

**Comment by mpeng5120** [comment]
好的，多谢

**Comment by JellyHell** [comment]
./gradlew assembleDebug失败

bogon:FirstBundle JellyHell$ ./gradlew assembleDebug --stacktrace
Parallel execution with configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/JellyHell/Desktop/Chrome下载/atlas/atlas-demo/FirstBundle/build.gradle' line: 14

* What went wrong:
A problem occurred evaluating root project 'FirstBundle'.
> java.lang.UnsupportedClassVersionError: com/taobao/android/builder/AtlasLibraryPlugin : Unsupported major.minor version 52.0

**Comment by jiawulu** [comment]
jdk版本过低了

**Comment by JellyHell** [comment]
@jiawulu ok 了
