### ISSUE TITLE
[demo]:AAPT issue

### ISSUE THREAD

**Issue by Visualrainy** [alibaba/atlas#121]
在拉下demo的代码，命令行run ./gradlew build 时（Mac OSX），出现了一下错误信息，显示AAPT err：
00:16:42.757 [INFO] [com.android.builder.core.AtlasBuilder] Job is in error mode, cause :
00:16:42.757 [ERROR] [com.android.builder.core.AtlasBuilder] AAPT err(Facade for 2094770679) : No Delegate set : lost message:Unknown command
00:16:42.757 [ERROR] [com.android.builder.core.AtlasBuilder] AAPT err(Facade for 439856725) : No Delegate set : lost message: ERROR: Unable to open PNG file
00:16:42.756 [ERROR] [com.android.builder.core.AtlasBuilder] AAPT err(Facade for 1191252503) : No Delegate set : lost message:Unknown command
00:16:42.758 [ERROR] [com.android.builder.core.AtlasBuilder] AAPT err(Facade for 439856725) : No Delegate set : lost message:Unknown command
00:16:42.758 [INFO] [com.android.builder.core.AtlasBuilder] Thread(png-cruncher_4): submitting job Cruncher abc_ab_share_pack_mtrl_alpha.9.png to 1980229906
00:16:42.759 [INFO] [com.android.builder.core.AtlasBuilder] Process(1980229906) abc_ab_share_pack_mtrl_alpha.9.png job:QueuedJob{
title=Cruncher abc_ab_share_pack_mtrl_alpha.9.png,
task={from=/Users/pchen/.android/build-cache/dce375ca51cc7887912fc373db9a935f4c75ffc5/output/res/drawable-xhdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png, to=/Users/pchen/tw/android/atlas/atlas-demo/AtlasDemo/app/build/intermediates/res/merged/release/drawable-xhdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png},
future=com.google.common.util.concurrent.SettableFuture@78c019a2}
00:16:42.759 [INFO] [com.android.builder.core.AtlasBuilder] Process(1980229906) length = 138:146
00:16:42.760 [INFO] [com.android.builder.core.AtlasBuilder] Processed(1980229906) abc_ab_share_pack_mtrl_alpha.9.png job:QueuedJob{
title=Cruncher abc_ab_share_pack_mtrl_alpha.9.png,
task={from=/Users/pchen/.android/build-cache/dce375ca51cc7887912fc373db9a935f4c75ffc5/output/res/drawable-xhdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png, to=/Users/pchen/tw/android/atlas/atlas-demo/AtlasDemo/app/build/intermediates/res/merged/release/drawable-xhdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png},
future=com.google.common.util.concurrent.SettableFuture@78c019a2}
00:16:42.760 [INFO] [com.android.builder.core.AtlasBuilder] AAPT out(Facade for 1980229906): Crunching
00:16:42.760 [INFO] [com.android.builder.core.AtlasBuilder] AAPT out(Facade for 1980229906): -> QueuedJob{
title=Cruncher abc_ab_share_pack_mtrl_alpha.9.png,

**Comment by fuzhengchao** [comment]
@Visualrainy 哥们，你这个问题解决了吗

**Comment by hwjump** [comment]
第2次 Crunching png貌似会有问题。我们还在排查。  你们最好打之前 clean一下。

**Comment by hwjump** [comment]
如果还有问题，最好进钉钉群，这样响应快一些
