### ISSUE TITLE
热部署抛出异常 java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by 821917380** [alibaba/atlas#122]
throws the java.lang.reflect.InvocationTargetException in android.taobao.atlas.framework.Framework.java 1122 lines, and the parameters like this:  Object b = cons.newInstance(bundleDir, files[i],Framework.containerVersion,dexPatchVersion); 
bundleDir: /data/user/0/com.taobao.demo/files/storage/com.taobao.maindex
files[i]: /data/user/0/com.taobao.demo/cache/atlas_update/libcom_taobao_maindex.so
Framework.containerVersion: "1.0.1"
dexPatchVersion: 0

**Comment by 821917380** [comment]
Can anyone help me?

**Comment by hwjump** [comment]
请pull一下最新代码。  如果还有问题，最好进钉钉群，响应会快一些。谢谢
