### ISSUE TITLE
InitBundleInfoByVersionIfNeed has a bug

### ISSUE THREAD

**Issue by 821917380** [alibaba/atlas#123]
在AtlasBundleInfoManager这个类中的第470行有一个方法名叫 InitBundleInfoByVersionIfNeed，
其中有一句代码是这样的： String bundleInfoStr =
 (String)RuntimeVariables.getFrameworkProperty("bundleInfo");
如果我在app的gradle中不添加任何的bundle依赖，则这个bundleInfo会有两种结果，一个是空数组，另一个是null，而如果是null的话，底部的处理中则抛出异常，导致程序崩溃。

**Comment by hwjump** [comment]
yes， 我们目前没有 没有bundle的case， 我们会改一下这个问题。
