### ISSUE TITLE
动态部署失败提示：Error:Execution failed for task ':atlasLeJuPos:packageDebugAwbs'. > package devpos-LeJuPos failed

### ISSUE THREAD

**Issue by wanglu123run** [alibaba/atlas#125]
目前只使用了远程加载组件功能，有时候可以直接部署到手机，有时候却不行，报错如下：
Error:Execution failed for task ':atlasLeJuPos:packageDebugAwbs'.
> package 动态部署项目名 failed

**Comment by neilnee** [comment]
我遇到了类似的问题, clean以后在执行assembleRelease会出现空指针, 再执行一次assembleRelease则正常执行.
之后把atlasplugin的版本升级到2.3.1.rc13后解决了这个问题

**Comment by hwjump** [comment]
升级一下 插件版本   建议用demo里的版本  或者 我们打了tag的版本。   因为jcenter不能用snapshot，所以可能有些版本是我们中间测试的版本，不稳定
