### ISSUE TITLE
[use]:运行提示Provider与手淘冲突

### ISSUE THREAD

**Issue by niuyunedu** [alibaba/atlas#126]
Studio提示:
Installation failed with message Failed to finalize session : INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/xxxx.xxxx.xxxx-1: Can't install because provider name android.taobao.atlas.runtime.newcomponent.ATLASPROXY_channel_Provider (in package xxxx.xxxx.xxxx) is already used by com.taobao.taobao.

build目录下生成了这两个文件. 
![image](https://cloud.githubusercontent.com/assets/17402719/26041220/bcecdcae-395d-11e7-8194-0e8733c76ba4.png)
看了下Demo的build目录, 没有这个,  求问是哪里出问题了呢?

**Comment by hwjump** [comment]
因为你刚好有个进程叫channel，导致的。  急的话你升级下最新的atlasplugin和atlascore 已经解了这个问题了。  最近我们会发tag，然后就没有这个问题了。
