### ISSUE TITLE
基准包打包发布manven出现找不到maven-metadata.xml

### ISSUE THREAD

**Issue by myqhit** [alibaba/atlas#128]
1. 打基准包成功，并且在本地maven仓库去找AP-debug基准包，发现也成功发布到本地仓库，但是在命令行下面会显示如下提示：
:app:DiffBundleInfoDebug UP-TO-DATE
:app:processDiffResourcesDebug SKIPPED
:app:CreateDebugTPatchDiffApk SKIPPED
:app:CreateDebugTPatch SKIPPED
:app:assembleDebug
:app:generatePomFileForMavenPublication
:app:publishMavenPublicationToMavenLocalRepository
**Could not find metadata com.taobao.android.atlasdemo:AP-debug/maven-metadata.xml
 in remote (file:/D:/m2_repository/)**
:app:publish

请问是什么原因，会影响打patch包吗？

**Comment by hwjump** [comment]
会， AP包是打patch包的基础。基线。  diff是和它来的
你这个问题可能还是maven配置的问题。   maven publish的时候没有生成maven-detadata

**Comment by myqhit** [comment]
在maven本地是有maven-metadata.xml 文件生成的

**Comment by hwjump** [comment]
我感觉还是你maven环境的问题。log提示的目录真的有maven-metadata.xml?
