### ISSUE TITLE
[use]:请问如何处理动态部署（patch）的版本控制问题

### ISSUE THREAD

**Issue by jasonfresher** [alibaba/atlas#131]
动态部署版本是如何控制的，比如手机本地是1.0.0版本，构建出新版本为1.0.1
`../gradlew clean assembleDebug -DapVersion=1.0.0 -DversionName=1.0.1`

然后会得到update.json以及tpatch文件。

**在本地会有一段关于升级业务的逻辑，从服务器获取到update.json跟tpatch文件后进行动态部署，部署成功之后，需要如何判断当前版本已经是1.0.1，不需要再次从服务器下载patch更新**

**Comment by hwjump** [comment]
-DversionName=1.0.1   最后生成的versionName版本部署成功后会改变代码里面到packageManager里面拿applicationInfo的versionName的值，通过这个值，传给服务端给不同的tpach文件。

比如说基线 1.0.0，动态部署升级到1.0.1  这时候就只会生成1个tpach文件（1.0.1@1.0.0），然后你继续动态部署1.0.2，这时候线上会有两个存量版本 1.0.0和1.0.1，这时候你要生成两个tpatch文件（（1.0.2@1.0.1）（1.0.2@1.0.0）），根据你传给服务端的versionName给不同的tpatch 做部署。

**Comment by huaf22** [comment]
@hwjump  可以一次打出 1.0.2@1.0.1 和 1.0.2@1.0.0 的 tpatch包吗? 如果可以的话需要这么操作? 如果不行的话, 怎么用两个已经保存在 maven 上的 ap 包打包出 tpatch? demo和教程中都是在assemble过程中打patch包
