### ISSUE TITLE
[use]:com.taobao.atlas.update.exception.MergeException: merge failed!

### ISSUE THREAD

**Issue by jcdee** [alibaba/atlas#136]
报这个错误的原因是什么？
window平台
awb包是完整的。

**Comment by hwjump** [comment]
mergeException说明你走到动态部署逻辑了。 和awb包没关系。  和打的tpatch包有关系。  最好断点调试一下。拒以前经验，多半是tpatch包打的有问题。基线ap不对导致的。

**Comment by hwjump** [comment]
如果还有问题，欢迎进钉钉群沟通。会更及时一些，也可以和其他开发交流，可能他们解决了呢

**Comment by yangzhiqian** [comment]
你是不是在主线程中update了，试试在子线执行。
