### ISSUE TITLE
[demo]:怎么动态更新主客户端app里面的内容？

### ISSUE THREAD

**Issue by jdsjlzx** [alibaba/atlas#138]
执行../gradlew clean assembleDebug -DapVersion=1.0.0 -DversionName=1.0.1命令，然后将tpatch-debug/update.json、tpatch-debug/patch-*.tpatch   push到 /sdcard/Android/data/com.android.dzatlas/cache目录下，bundle能做到动态更新，主客户端app里面的内容不能动态更新（修改了布局文件比如新增控件或者更新string.xml 不能更新），这个怎么解决呢？

补充：经过尝试，执行../gradlew clean assembleDebug -DapVersion=1.0.0 -DversionName=1.0.1命令可以动态修改逻辑代码，不能修改布局文件！
谢谢！

其中update.json如下所示：

{
	"baseVersion":"1.0.0",
	"updateBundles":[
		{
			"dependency":[],
			"isMainDex":false,
			"name":"com.android.homebundle",
			"version":"1.0.0@unspecified"
		},
		{
			"dependency":[],
			"isMainDex":false,
			"name":"com.android.loadingbundle",
			"version":"1.0.0@unspecified"
		},
		{
			"isMainDex":true,
			"name":"com.taobao.maindex",
			"version":"1.0.0@1.0.1"
		}
	],
	"updateVersion":"1.0.1"
}

"name":"com.taobao.maindex", 这个我能改为自己的包名吗？

**Comment by hwjump** [comment]
1. 请用dev分支同步的atlas plugin。  老版本资源diff有问题。
2. 目前不能，打包插件写死了。 要改的话需要修改打包插件 以及atlas-update代码。可以自己研究下。
