### ISSUE TITLE
 buildApk.sh 构建异常

### ISSUE THREAD

**Issue by JellyHell** [alibaba/atlas#14]
以下是log
bogon:app JellyHell$ sh buildApk.sh -stacktrace
(1) 构建app， 生成 apk 和 ap， 同时把 ap 文件发布到本地仓库
Parallel execution with configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/JellyHell/Desktop/atlas/atlas-demo/app/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating root project 'app'.
> java.lang.UnsupportedClassVersionError: com/taobao/android/builder/AtlasApplicationPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.305 secs
cat: build/publications/maven/pom-default.xml: No such file or directory
ap 模块发布到本地仓库成功
(3) 安装基线apk
adb install -r build/outputs/apk/app-debug.apk

**Comment by jiawulu** [comment]
请使用 jdk 1.8

**Comment by JellyHell** [comment]
@jiawulu 解决了 谢谢

**Comment by JellyHell** [comment]
@jiawulu 
bogon:app $ sh buildApk.sh

:FirstBundle:sourcesJar
:FirstBundle:publishMavenPublicationToMavenLocalRepository FAILED
prepareAwbsxx293 | 4

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':FirstBundle:publishMavenPublicationToMavenLocalRepository'.
> Failed to publish publication 'maven' to repository 'MavenLocal'
   > Invalid publication 'maven': artifact file does not exist: '/Users/JellyHell/Desktop/atlas/atlas-demo/app/FirstBundle/build/outputs/awb/FirstBundle-relse.awb'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED


FirstBundle-relse.awb是怎么生成的呢？

**Comment by Jiepeixuan** [comment]
我使用Android Studio直接进行public就ok,但是使用buildApk.sh 也报了上述异常 我的jdk是1.8.0_121

**Comment by JellyHell** [comment]
@Jiepeixuan AS直接publish的apk能正常运行么

**Comment by Jiepeixuan** [comment]
@JellyHell   我使用AS直接打开那个demo中的app  然后按照shell 先publish 再install

**Comment by JellyHell** [comment]
@Jiepeixuan  运行后好像不能跳转到FirstBundle的FirstBundleActivity

**Comment by Jiepeixuan** [comment]
@JellyHell 是的  所以我想按照这个shell运行 但是还是报你上面的错误 @jiawulu

**Comment by Jiepeixuan** [comment]
@JellyHell 我可以打开那个FirstBundleActivity  但是第二个更新的无法使用

**Comment by jiawulu** [comment]
1. 这个版本的插件是不支持 compile project 这种依赖类型的 ，所以 app 和 FirstBundle 是2个完全独立的模块 （会在2.3.0 版本支持）

2.  FirstBundle 修改后需要做单独的 publish， 具体见 https://github.com/alibaba/atlas/issues/12#issuecomment-286324522

3.  app 是通过坐标依赖到 FirstBundle 进行构建的 ， 所以不会去再去执行 FirstBundle 的构建了。

**Comment by 317764920** [comment]
@jiawulu 现在只能通过maven来进行依赖咯？

**Comment by jiawulu** [comment]
@317764920 是的， 要等到 2.3.0 的版本

**Comment by xufan** [comment]
所以 现在有一些公共库lib 不能本地compile project 而只能用AAR吗？感觉 Demo有点过于简单了 没有解释清楚一些限制

**Comment by jiawulu** [comment]
所有的非 bundle （awb） 的依赖 都是可以 compile project 的，
