### ISSUE TITLE
提示libdalvikpatch.so文件找不到

### ISSUE THREAD

**Issue by whosmyqueen** [alibaba/atlas#143]
大神看看怎么回事
手机型号  华为P9
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.zhph.zhenghaofengqiu-1/base.apk"],nativeLibraryDirectories=[/data/app/com.zhph.zhenghaofengqiu-1/lib/arm64, /data/app/com.zhph.zhenghaofengqiu-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]] couldn't find "libdalvikpatch.so"

**Comment by hwjump** [comment]
不影响使用。忽略该提示
