### ISSUE TITLE
Could not resolve com.taobao.android:atlas_core:5.0.7.11.

### ISSUE THREAD

**Issue by John901190** [alibaba/atlas#151]
Error:A problem occurred configuring project ':activitygroupcompat'.
> Could not resolve all dependencies for configuration ':activitygroupcompat:_debugPublishCopy'.
   > Could not resolve com.taobao.android:atlas_core:5.0.7.11.
     Required by:
         project :activitygroupcompat
      > No cached version of com.taobao.android:atlas_core:5.0.7.11 available for offline mode.

**Comment by hwjump** [comment]
换用dev分支试试。
