### ISSUE TITLE
[use]:调用 AtlasUpdater.update(info, patchFile)提示报错 prepare client error

### ISSUE THREAD

**Issue by yuqiyich** [alibaba/atlas#155]
在生成了patch和json文件之后，推到手机上进行merge,在Application中调用 AtlasUpdater.update(info, patchFile);，报了如下错误  prepare client error，bindService时bind这个"com.taobao.atlas.dexmerge.DexMergeService"不成功，而且在bind的过程中会卡会卡很久，具体报错如下:

07-06 18:33:32.000 9035-9035/com.xuebansoft.xinghuo.manager W/System.err: java.lang.RuntimeException: prepare client error
07-06 18:33:32.000 9035-9035/com.xuebansoft.xinghuo.manager W/System.err:     at com.taobao.atlas.update.util.PatchMerger.getMergeClient(PatchMerger.java:210)
07-06 18:33:32.020 9035-9035/com.xuebansoft.xinghuo.manager W/System.err:     at com.taobao.atlas.update.util.PatchMerger.merge(PatchMerger.java:106)
07-06 18:33:32.020 9035-9035/com.xuebansoft.xinghuo.manager W/System.err:     at com.taobao.atlas.update.AtlasUpdater.update(AtlasUpdater.java:47)

**Comment by Huyamin150** [comment]
请问你解决了这个问题了么？我也碰到了

**Comment by victorfan336** [comment]
我也遇到了，怎么解决的呀？有人知道吗

**Comment by lvsj** [comment]
此问题已经解决了，参考 #232 。
