### ISSUE TITLE
[use]:宿主apk的资源无法更新，大大们什么时候能解决下这个问题？

### ISSUE THREAD

**Issue by yuqiyich** [alibaba/atlas#156]
请按照下面的规则提交您的issue，符合标准的issue会被优先处理,
请先查看有没有同类型的issue已经存在.

1. demo问题的issue格式： [demo]:title

   title尽量反应问题的状况，如果是编译问题或者无法运行，正文写明是windows还是mac，如果是不清楚如何使用demo，请先查看https://github.com/alibaba/atlas/blob/master/atlas-demo/README.zh_cn.md
     
2. 容器功能接入或者如何使用的答疑：[use]:title
3. 提新需求的格式：[feature]:title

**Comment by hwjump** [comment]
宿主资源部署从开源时就是可以更新的。 具体你要看打出来的tpatch包是不是包含了diff的资源。如果没有，先对齐下atlasplugin是不是最新release版本。
