### ISSUE TITLE
接入tinker热更新会产生HOOK冲突么？

### ISSUE THREAD

**Issue by linchangjian** [alibaba/atlas#158]
07-13 19:41:39.036 6754-6754/? E/RuntimeUtils: - RuntimeUtils setVerificationEnabled: enabled=false, success=true
07-13 19:41:39.036 6754-6754/? W/dalvikvm: Class resolved by unexpected DEX: Landroid/taobao/atlas/bundleInfo/AtlasBundleInfoManager;(0x423b6270):0x5fd73000 ref [Landroid/taobao/atlas/bundleInfo/BundleListingUtil;] Landroid/taobao/atlas/bundleInfo/BundleListingUtil;(0x423b6270):0x61d5a000
07-13 19:41:39.036 6754-6754/? W/dalvikvm: (Landroid/taobao/atlas/bundleInfo/AtlasBundleInfoManager; had used a different Landroid/taobao/atlas/bundleInfo/BundleListingUtil; during pre-verification)
07-13 19:41:39.036 6754-6754/? W/System.err: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
07-13 19:41:39.036 6754-6754/? W/System.err:     at android.taobao.atlas.bundleInfo.AtlasBundleInfoManager.<init>(AtlasBundleInfoManager.java:258)
07-13 19:41:39.036 6754-6754/? W/System.err:     at android.taobao.atlas.bundleInfo.AtlasBundleInfoManager.instance(AtlasBundleInfoManager.java:245)
07-13 19:41:39.036 6754-6754/? W/System.err:     at android.taobao.atlas.framework.Framework.startup(Framework.java:339)
07-13 19:41:39.036 6754-6754/? W/System.err:     at android.taobao.atlas.framework.Atlas.startup(Atlas.java:328)
07-13 19:41:39.036 6754-6754/? W/System.err:     at android.taobao.atlas.bridge.BridgeApplicationDelegate.onCreate(BridgeApplicationDelegate.java:429)
07-13 19:41:39.036 6754-6754/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
07-13 19:41:39.036 6754-6754/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
07-13 19:41:39.036 6754-6754/? W/System.err:     at android.taobao.atlas.startup.AtlasBridgeApplication.onCreate(AtlasBridgeApplication.java:360)
07-13 19:41:39.036 6754-6754/? W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
07-13 19:41:39.036 6754-6754/? W/System.err:     at android.taobao.atlas.runtime.InstrumentationHook.callApplicationOnCreate(InstrumentationHook.java:1043)
07-13 19:41:39.036 6754-6754/? W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4459)
07-13 19:41:39.036 6754-6754/? W/System.err:     at android.app.ActivityThread.access$1500(ActivityThread.java:138)
07-13 19:41:39.036 6754-6754/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1260)
07-13 19:41:39.036 6754-6754/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-13 19:41:39.036 6754-6754/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
07-13 19:41:39.036 6754-6754/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5132)
07-13 19:41:39.036 6754-6754/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
07-13 19:41:39.036 6754-6754/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
07-13 19:41:39.036 6754-6754/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
07-13 19:41:39.036 6754-6754/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
07-13 19:41:39.036 6754-6754/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
07-13 19:41:39.046 6754-6754/? W/dalvikvm: Class resolved by unexpected DEX: Landroid/taobao/atlas/bundleInfo/AtlasBundleInfoManager;(0x423b6270):0x5fd73000 ref [Landroid/taobao/atlas/bundleInfo/BundleListingUtil;] Landroid/taobao/atlas/bundleInfo/BundleListingUtil;(0x423b6270):0x61d5a000
07-13 19:41:39.046 6754-6754/? W/dalvikvm: (Landroid/taobao/atlas/bundleInfo/AtlasBundleInfoManager; had used a different Landroid/taobao/atlas/bundleInfo/BundleListingUtil; during pre-verification)
07-13 19:41:39.046 6754-6754/? W/System.err: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.taobao.atlas.bundleInfo.AtlasBundleInfoManager.<init>(AtlasBundleInfoManager.java:258)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.taobao.atlas.bundleInfo.AtlasBundleInfoManager.instance(AtlasBundleInfoManager.java:245)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.taobao.atlas.framework.Framework.startup(Framework.java:339)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.taobao.atlas.framework.Atlas.startup(Atlas.java:328)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.taobao.atlas.bridge.BridgeApplicationDelegate.onCreate(BridgeApplicationDelegate.java:429)
07-13 19:41:39.046 6754-6754/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
07-13 19:41:39.046 6754-6754/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.taobao.atlas.startup.AtlasBridgeApplication.onCreate(AtlasBridgeApplication.java:360)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.taobao.atlas.runtime.InstrumentationHook.callApplicationOnCreate(InstrumentationHook.java:1043)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4459)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.app.ActivityThread.access$1500(ActivityThread.java:138)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1260)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5132)
07-13 19:41:39.046 6754-6754/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
07-13 19:41:39.046 6754-6754/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
07-13 19:41:39.046 6754-6754/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
07-13 19:41:39.046 6754-6754/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
07-13 19:41:39.046 6754-6754/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
07-13 19:41:39.046 6754-6754/? W/System.err: java.lang.reflect.InvocationTargetException
07-13 19:41:39.046 6754-6754/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
07-13 19:41:39.046 6754-6754/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.taobao.atlas.startup.AtlasBridgeApplication.onCreate(AtlasBridgeApplication.java:360)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.taobao.atlas.runtime.InstrumentationHook.callApplicationOnCreate(InstrumentationHook.java:1043)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4459)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.app.ActivityThread.access$1500(ActivityThread.java:138)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1260)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5132)
07-13 19:41:39.046 6754-6754/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
07-13 19:41:39.046 6754-6754/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
07-13 19:41:39.046 6754-6754/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
07-13 19:41:39.046 6754-6754/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
07-13 19:41:39.046 6754-6754/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
07-13 19:41:39.046 6754-6754/? W/System.err: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: parse bundleinfo failed
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.taobao.atlas.framework.Atlas.startup(Atlas.java:330)
07-13 19:41:39.046 6754-6754/? W/System.err:     at android.taobao.atlas.bridge.BridgeApplicationDelegate.onCreate(BridgeApplicationDelegate.java:429)
07-13 19:41:39.046 6754-6754/? W/System.err: 	... 16 more
07-13 19:41:39.046 6754-6754/? W/System.err: Caused by: java.lang.RuntimeException: parse bundleinfo failed
07-13 19:41:39.056 6754-6754/? W/System.err:     at android.taobao.atlas.bundleInfo.AtlasBundleInfoManager.<init>(AtlasBundleInfoManager.java:279)
07-13 19:41:39.056 6754-6754/? W/System.err:     at android.taobao.atlas.bundleInfo.AtlasBundleInfoManager.instance(AtlasBundleInfoManager.java:245)
07-13 19:41:39.056 6754-6754/? W/System.err:     at android.taobao.atlas.framework.Framework.startup(Framework.java:339)
07-13 19:41:39.056 6754-6754/? W/System.err:     at android.taobao.atlas.framework.Atlas.startup(Atlas.java:328)
07-13 19:41:39.056 6754-6754/? W/System.err: 	... 17 more
07-13 19:41:39.056 6754-6754/? E/com.sgs.unite.receiver.TcpNotifyReceiver.onReceive(L:16): Action : com_sf_tcp_network_action
07-13 19:41:39.056 6754-6754/? W/dalvikvm: Class resolved by unexpected DEX: Landroid/taobao/atlas/runtime/ActivityManagerDelegate;(0x423b6270):0x5fd73000 ref [Landroid/taobao/atlas/runtime/ServiceDetector;] Landroid/taobao/atlas/runtime/ServiceDetector;(0x423b6270):0x61d5a000
07-13 19:41:39.056 6754-6754/? W/dalvikvm: (Landroid/taobao/atlas/runtime/ActivityManagerDelegate; had used a different Landroid/taobao/atlas/runtime/ServiceDetector; during pre-verification)
07-13 19:41:39.106 6754-6754/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/data/com.sgs.unite/tinker_temp/temp.apk is not exist, just return

**Comment by WeaponZhi** [comment]
接入 tinker 混合使用会有问题吗

**Comment by Yellow5A5** [comment]
所以结果是？?

**Comment by hwjump** [comment]
接入atlas就具备了修复的能力。
