### ISSUE TITLE
What wrong? bad dex patch file magic: [100, 101, 120, 10, 48, 51]

### ISSUE THREAD

**Issue by linchangjian** [alibaba/atlas#160]
07-15 23:48:36.337 7120-7682/com.taobao.demo:dexmerge W/System.err: java.lang.IllegalStateException: bad dex patch file magic: [100, 101, 120, 10, 48, 51]
07-15 23:48:36.338 7120-7682/com.taobao.demo:dexmerge W/System.err:     at com.taobao.common.dexpatcher.struct.DexPatchFile.init(DexPatchFile.java:71)
07-15 23:48:36.338 7120-7682/com.taobao.demo:dexmerge W/System.err:     at com.taobao.common.dexpatcher.struct.DexPatchFile.<init>(DexPatchFile.java:65)
07-15 23:48:36.338 7120-7682/com.taobao.demo:dexmerge W/System.err:     at com.taobao.common.dexpatcher.DexPatchApplier.<init>(DexPatchApplier.java:76)
07-15 23:48:36.338 7120-7682/com.taobao.demo:dexmerge W/System.err:     at com.taobao.atlas.dexmerge.MergeExcutorServices.dexMergeInternal(MergeExcutorServices.java:196)
07-15 23:48:36.338 7120-7682/com.taobao.demo:dexmerge W/System.err:     at com.taobao.atlas.dexmerge.MergeExcutorServices.access$000(MergeExcutorServices.java:20)
07-15 23:48:36.338 7120-7682/com.taobao.demo:dexmerge W/System.err:     at com.taobao.atlas.dexmerge.MergeExcutorServices$MergeTask$1.prepareMerge(MergeExcutorServices.java:160)
07-15 23:48:36.338 7120-7682/com.taobao.demo:dexmerge W/System.err:     at com.taobao.atlas.dexmerge.MergeTool.dexMerge(MergeTool.java:278)
07-15 23:48:36.338 7120-7682/com.taobao.demo:dexmerge W/System.err:     at com.taobao.atlas.dexmerge.MergeTool.createNewBundleInternal(MergeTool.java:242)
07-15 23:48:36.338 7120-7682/com.taobao.demo:dexmerge W/System.err:     at com.taobao.atlas.dexmerge.MergeTool.mergePrepare(MergeTool.java:30)
07-15 23:48:36.338 7120-7682/com.taobao.demo:dexmerge W/System.err:     at com.taobao.atlas.dexmerge.MergeExcutorServices$MergeTask.call(MergeExcutorServices.java:148)
07-15 23:48:36.338 7120-7682/com.taobao.demo:dexmerge W/System.err:     at com.taobao.atlas.dexmerge.MergeExcutorServices$MergeTask.call(MergeExcutorServices.java:128)
07-15 23:48:36.338 7120-7682/com.taobao.demo:dexmerge W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-15 23:48:36.338 7120-7682/com.taobao.demo:dexmerge W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-15 23:48:36.338 7120-7682/com.taobao.demo:dexmerge W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-15 23:48:36.338 7120-7682/com.taobao.demo:dexmerge W/System.err:     at java.lang.Thread.run(Thread.java:818)
07-15 23:48:36.339 23177-23195/com.taobao.demo E/DexMergeClient: merge Failed:com.taobao.firstbundle
07-15 23:48:36.341 23177-7681/com.taobao.demo D/DexMergeClient: dexMerge  false16 ms
07-15 23:48:36.342 7120-7141/com.taobao.demo:dexmerge E/mergeTask: merge all finish but failed!
07-15 23:48:36.345 23177-7681/com.taobao.demo W/System.err: com.taobao.atlas.update.exception.MergeException: merge failed!
07-15 23:48:36.345 23177-7681/com.taobao.demo W/System.err:     at com.taobao.atlas.update.util.PatchMerger.merge(PatchMerger.java:113)
07-15 23:48:36.345 23177-7681/com.taobao.demo W/System.err:     at com.taobao.demo.update.Updater.update(Updater.java:263)
07-15 23:48:36.345 23177-7681/com.taobao.demo W/System.err:     at com.taobao.demo.WelcomActivity$2$1.run(WelcomActivity.java:253)
07-15 23:48:36.345 23177-7681/com.taobao.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)
07-15 23:48:36.345 23177-7681/com.taobao.demo W/System.err: com.taobao.atlas.update.exception.MergeException: merge failed!
07-15 23:48:36.346 23177-7681/com.taobao.demo W/System.err:     at com.taobao.atlas.update.util.PatchMerger.merge(PatchMerger.java:120)
07-15 23:48:36.346 23177-7681/com.taobao.demo W/System.err:     at com.taobao.demo.update.Updater.update(Updater.java:263)
07-15 23:48:36.346 23177-7681/com.taobao.demo W/System.err:     at com.taobao.demo.WelcomActivity$2$1.run(WelcomActivity.java:253)
07-15 23:48:36.346 23177-7681/com.taobao.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by lilongAAAA** [comment]
Please use atlasupdate version:1.1.4.10
