### ISSUE TITLE
请问下dexinterpret\dalvikhack\dalvikpatch几个so里面的代码能开源吗？

### ISSUE THREAD

**Issue by houliang** [alibaba/atlas#161]
如题：
请问下dexinterpret\dalvikhack\dalvikpatch几个so里面的代码能开源吗？

**Comment by hwjump** [comment]
暂时没有计划。

**Comment by hejie** [comment]
最初是 andfix 改的,你也可以自己做
针对art和dalvik工具类进行优化

**Comment by houliang** [comment]
可否提供大致的思路，谢谢！






在 2017-12-27 16:29:43，"JIE" <notifications@github.com> 写道：


最初是 andfix 改的,你也可以自己做
针对art和dalvik工具类进行优化
