### ISSUE TITLE
[feature]:何时能够支持flavor

### ISSUE THREAD

**Issue by woodphone** [alibaba/atlas#164]
atlas何时能够支持flavor

**Comment by hwjump** [comment]
参见 https://github.com/alibaba/atlas/wiki/atlas%E6%8F%92%E4%BB%B6%E4%B8%8B%E6%9E%84%E5%BB%BA%E7%89%B9%E6%AE%8A%E5%8C%85%E7%9A%84%E6%AD%A3%E7%A1%AE%E5%A7%BF%E5%8A%BF
