### ISSUE TITLE
模块间调用的时候怎么传递参数

### ISSUE THREAD

**Issue by 296468465** [alibaba/atlas#167]
Intent intent = new Intent();
intent.setClassName(WiFiMainActivity.this,"com.ihangmei.wangfan.newsmodule.NewsOtherMainActivity");
intent.putExtra("testdata",1);
startActivity(intent);
这样调用时不行的

**Comment by hwjump** [comment]
可以的。   android上的那些传参方式都可以的。

**Comment by 296468465** [comment]
但是我试过，不能获取到参数，你能发一个完整版的调用方式和参数获取代码吗？ 谢谢

**Comment by huaf22** [comment]
@296468465 
是否 com.ihangmei.wangfan.newsmodule.NewsOtherMainActivity 类所在的 Bundle 还没有安装完成？

**Comment by hwjump** [comment]
没有安装，会先做安装的。一般的传参方式都支持的。这里面要特别注意Parcelable对象的传递。

**Comment by huaf22** [comment]
@hwjump " 特别注意Parcelable对象 " 是什么意思？ 这个对象必须放到主 APK 中吗？

**Comment by hwjump** [comment]
不是必须的。 这里面要理解atlas classloader加载类的原理。而Parcelable对象的反序列化是需要classloader的。  如果有在 bundle里传这个，而刚好有代码在主dex里面去getbundle里的东西，就会触发Parcelable的反序列化。 这时候如果classloader找不到类就会报classnotfound错误

**Comment by huaf22** [comment]
@hwjump 
```
activity.getIntent().setExtrasClassLoader(classLoader);
```
如果设置上面这个 classloader 为 BundleClassloader， 那代码在主dex里面去getbundle里的东西，也会报classnotfound错误吗？

**Comment by hwjump** [comment]
如果能确定只有Parcelable对象的BundleClassloader是可以的。
