### ISSUE TITLE
[demo]secondbundle依赖公共publicbundlebundle 并新建一个activity 里调用公共bundle里Tools类的方法，报错

### ISSUE THREAD

**Issue by akingyin1987** [alibaba/atlas#169]
Caused by: java.lang.NoClassDefFoundError: com/taobao/publicBundle/Tools
                                                                     at com.taobao.secondbundle.ShareDataActivity.onCreate(ShareDataActivity.java:19)

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    providedCompile project(':middlewarelibrary')
    providedCompile project(':publicbundle')
    compile project(":secondbundlelibrary");
    providedCompile 'com.android.support:appcompat-v7:25.3.1'
    providedCompile 'com.android.support:support-v4:25.3.1'
    providedCompile 'com.android.support.constraint:constraint-layout:1.0.0-alpha8'

}

**Comment by akingyin1987** [comment]
原来是要手动配置bundleBaseInfoFile

**Comment by Huyamin150** [comment]
@akingyin1987 哥们你是直接把frist里面的json文件copy到second下面就可以实现依赖了么，我这样做还是报错了

**Comment by akingyin1987** [comment]
你要改里面的参数呀，你要依赖哪个bundle 里面就写哪个"dependency": ["com.taobao.publicBundle"]

**Comment by ZhangKuixun** [comment]
> 原来是要手动配置bundleBaseInfoFile
我在demo工程中没有找到bundleBaseInfoFile.json
