### ISSUE TITLE
如何更换远程bundle及校验安全性

### ISSUE THREAD

**Issue by leidroid** [alibaba/atlas#173]
1.远程bundle小更新是可以跟本地bundle更新方法一样，如果我远程bundle进行了大的改动，我想进行替换，下载下来之后如何替换之前的远程bundle
2.远程bundle的安全性如何校验，拿到远程bundle的签名直接跟宿主的签名比对吗？

**Comment by hwjump** [comment]
大改动和小改动一样的逻辑，重新打包生成新的远程bundle放远端。 
安全性，可以有很多种校验，签名啊 md5啊 等等，不过需要你自己加上去。

**Comment by leidroid** [comment]
谢谢你的回复。重新生成新的远程bundle so文件，但是之前的用户已经安装了旧的bundle，此时是不是要先调用uninstallBundle 卸载掉旧的，再装新的。小更新貌似可以直接用tpatch，我想要的操作是直接替换整个bundle。安全性上，貌似我生成的bundle so文件是没有签名文件的，至于用md5，如果只是校验文件的md5，这个安全性没那么高

**Comment by leidroid** [comment]
bundle的签名可以用jarsigner生成，安全性问题已解决
