### ISSUE TITLE
window adb 安装APK问题。

### ISSUE THREAD

**Issue by supermoutant** [alibaba/atlas#174]
FATAL EXCEPTION: main
                                                                    Process: com.lenovo.octopus, PID: 19313
                                                                    java.lang.RuntimeException: Unable to instantiate application android.taobao.atlas.startup.AtlasBridgeApplication: java.lang.ClassNotFoundException: Didn't find class "android.taobao.atlas.startup.AtlasBridgeApplication" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.lenovo.octopus-1/base.apk"],nativeLibraryDirectories=[/data/app/com.lenovo.octopus-1/lib/arm, /system/fake-libs, /data/app/com.lenovo.octopus-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]

**Comment by leidroid** [comment]
把instant run关了看看

**Comment by supermoutant** [comment]
把instanr run 关了可以了，感谢。

**Comment by ZhangKuixun** [comment]
> 把instanr run 关了可以了，感谢。

我的依然不行
