### ISSUE TITLE
[use]:打包时生成的so文件，apk安装后会被删除吗？

### ISSUE THREAD

**Issue by CNlichao** [alibaba/atlas#178]
我查看了下安装后data/data 下应用的lib目录，打包时生成的so文件没有了，请问是安装后so包删除了吗？

**Comment by hwjump** [comment]
这是系统的install程序行为。部分手机存在so安装不完整行为，非atlas行为。 atlas针对这种情况做了兼容。 会直接从apk中解出来用。
