### ISSUE TITLE
插件支持databinding吗

### ISSUE THREAD

**Issue by xuelanghu120** [alibaba/atlas#18]

**Comment by yangb1993** [comment]
databinding是谷歌的官方数据绑定，与这个应该无关吧，自己加上去就行了啊

**Comment by xns1001** [comment]
与这个插件可有关了，你可以看看plugin的代码，几乎完全自定义的编译打包过程。不过我看到了databinding的相关task，应该是支持的。

**Comment by jiawulu** [comment]
支持的

**Comment by yangb1993** [comment]
那这样一般用到的butterknife支持吗
