### ISSUE TITLE
atlas patch更新后 布局中的fresco:actualImageScaleType="focusCrop"解析错误

### ISSUE THREAD

**Issue by LucyChen1** [alibaba/atlas#181]
修改布局，该布局中使用了fresco控件，其中有自定义属性。使用patch动态部署，加载该布局失败，错误是
Caused by：java.lang.NumberFormatException:Invalid int: “focusCrop” 。请问一下是怎么回事？

**Comment by hwjump** [comment]
当时应该解决了。用最新的打包插件即可
