### ISSUE TITLE
插件是否支持flavors

### ISSUE THREAD

**Issue by joyruby** [alibaba/atlas#182]
比如我有一个flavor：cibn。是否可以使用cibnBundleCompile引用插件。求解决方案。

问题：我自己试了一下，在配置阶段无法获取到flavor，导致无法根据定义的flavor，创建出所有的configuration。求解答！

**Comment by hwjump** [comment]
https://github.com/alibaba/atlas/wiki/atlas%E6%8F%92%E4%BB%B6%E4%B8%8B%E6%9E%84%E5%BB%BA%E7%89%B9%E6%AE%8A%E5%8C%85%E7%9A%84%E6%AD%A3%E7%A1%AE%E5%A7%BF%E5%8A%BF
