### ISSUE TITLE
动态部署，求教tpatch的版本问题

### ISSUE THREAD

**Issue by leidroid** [alibaba/atlas#183]
demo中打出来的tpatch，只能生成  "patch-现有版本@基线版本.tpatch" ，  "patch-现有版本@现有版本的前一个版本.tpatch"  两种吗？ 

假设我从1.0打补丁到1.1，有 patch-1.1@1.0.tpatch 文件生成 ， 然后再升到1.2，有patch-1.2@1.1.tpatch，和 patch-1.2-@1.0.tpatch两个文件，再升到1.3，有patch-1.3@1.2.tpatch，patch-1.3-@1.0.tpatch两个文件。但是如果现有版本是1.1的，要升到1.3，就找不到patch-1.3-@1.1.tpatch的文件了。

dev分支的代码好像没这个问题

**Comment by hwjump** [comment]
这里主要是 atlas-plugin的版本号用错了，老的atlas-plugin有这个bug。   请对齐我们release出来的版本号。https://github.com/alibaba/atlas/releases/tag/v5.0.7.42
