### ISSUE TITLE
abiFilters只是摆设

### ISSUE THREAD

**Issue by lizhangqu** [alibaba/atlas#188]
```
       ndk {
            abiFilters "armeabi-v7a"
        }
```

所有bundle包都丢了，所以armeabi就是必选项。项目中所有动态库都是armeabi-v7a的，之所以是armeabi-v7a而不是armeabi是因为部分第三方动态库只提供了armeabi-v7a，虽然armeabi-v7a下的动态库可以直接拷贝到armeabi下，但是这个过程涉及手动(虽然也可以写gradle脚本实现自动化)，一旦第三方lib升级(aar依赖)，会有风险。

armeabi可以进行做到最大范围的兼容，这点毫无疑问，而google最新版本的ndk-bundle默认构建动态库已经将armeabi移除了，所以目前市面上的机型armeabi-v7a也是绝对可以兼容掉的

个人建议，abiFilters生效的范围是除bundle包的其余动态库，bundle包无视abiFilters配置，无论配不配，bundle包都得打到armeabi下。但是这样又会带来另一个问题，即可能导致其他动态库找到armeabi下，导致找不到，从而抛Exception，所以是否应该默认将bundle包扔在armeabi下，再加个配置项决定具体扔在哪个abi下？

**Comment by hwjump** [comment]
你这个建议很不错。不过我们目前还在试验新特性。将所有bundle包放assert目录。这样就完美解决了abiFilters的问题。

**Comment by lizhangqu** [comment]
扔assets也是个不错的方法
