### ISSUE TITLE
[use]:packageId问题

### ISSUE THREAD

**Issue by weeklynote** [alibaba/atlas#189]
如果bundle的数量超过了packageid的可分配数量，怎么在继续加入bundle？

**Comment by hwjump** [comment]
你可以看一下 atlas-plugin的代码。 我们用了 resourceid的 高9位来做packageid。 所以理论上有127*8个段。 当然有些段和系统冲突，会规避掉。实际上也有1000多个段给这个app用了。  1000个对一个app来说还是比较难达到的天花板。如果真达到了。那有两条路，一是继续借1位过来。二是bundle做合并。
