### ISSUE TITLE
支持混淆吗

### ISSUE THREAD

**Issue by beasonshu** [alibaba/atlas#19]

**Comment by jiawulu** [comment]
支持

**Comment by wuuchao** [comment]
@jiawulu 我看到demo中跳转是这么写的intent.setClassName(WelcomActivity.this, "com.taobao.firstbundle.FirstBundleActivity");混淆之后包名和类名都变了，通过这种方式还可以正确跳转吗

**Comment by jiawulu** [comment]
@wuuchao 混淆不应该混淆4大组件的 keep住
