### ISSUE TITLE
公共组件必须放在Host中？

### ISSUE THREAD

**Issue by lizhangqu** [alibaba/atlas#190]
插件版本

```
 classpath "com.taobao.android:atlasplugin:2.3.3.rc29"
```

base bundle 

```
 compile 'com.squareup.okhttp3:okhttp:3.9.0'
```

发布到maven，坐标为 'com.atlas.test:base:1.0.0-SNAPSHOT'

lib1 bundle

```
compile 'com.atlas.test:base:1.0.0-SNAPSHOT'
```
发布到maven，坐标为 'com.atlas.test:lib1:1.0.0-SNAPSHOT'

host

```
   bundleCompile 'com.atlas.test:base:1.0.0-SNAPSHOT'
   bundleCompile 'com.atlas.test:lib1:1.0.0-SNAPSHOT'
```

结果

依赖冲突

```
decency冲突 : com.squareup.okhttp3:okhttp:3.9.0@jar:com.atlas.test:base:1.0.0-SNAPSHOT@awb,com.atlas.test:lib1:1.0.0-SNAPSHOT@awb
```

问：

基础SDK组件是否一定要扔在Host中去，能否扔在一个基础bundle中，供其他bundle调用？

**Comment by hwjump** [comment]
可以配置bundle间依赖。具体参考demo

**Comment by lizhangqu** [comment]
@hwjump 问题的关键不是能不能配置bundle间依赖，而是基础SDK组件是否一定要扔到Host,即com.squareup.okhttp3:okhttp:3.9.0是否一定要放在host，如果放在基础bundle中，就会报依赖错误
