### ISSUE TITLE
createAPatch属性是否已经移除

### ISSUE THREAD

**Issue by lizhangqu** [alibaba/atlas#193]
版本：atlas plugin rc29或rc30

插件中有createAPatch配置项，但该配置项并没有什么引用，整个插件中使用到该属性的值只有

```
if (patchConfig == null || !(patchConfig.isCreateAPatch() || patchConfig.isCreateTPatch())) {
                            return aaptOptions;
                        }
```

问 createAPatch是否已经废弃，如果有使用，请问使用的地方在哪里？如果已经废弃，请从插件中移除，避免造成混淆。真正有使用的应该是createTPatch配置

**Comment by hwjump** [comment]
createAPatch 没有用。

**Comment by lizhangqu** [comment]
如果没有使用，最好从插件中移除，避免引起混淆
