### ISSUE TITLE
动态部署所在线程问题

### ISSUE THREAD

**Issue by lizhangqu** [alibaba/atlas#194]
>动态部署必须发生在子线程，在主线程调用AtlasUpdater.update(info, patchFile);会出现merge failed，且异常为空指针，异常信息不明确，排除问题坑爹

不支持主线程的话，最好直接校验掉线程信息，否则会坑死很多人。

虽然在在主线程调用该方法是十分不合理的，但是为了排除问题方便，最好内部直接抛出一个不支持主线程的异常，而不是简简单单的merge failed，且文档里也没有明确说明动态部署不能发生在主线程，只有demo代码里有所体现（在子线程）

**Comment by Huyamin150** [comment]
很对，我被坑过
