### ISSUE TITLE
Mac 编译报错，Applications/Android%20Studio.app/Contents/gradle/gradle-3.3/caches/modules-2/files-2.1/com.taobao.android/aapt/2.3.1.rc2/af3b8747854c5ca14dc9a7aa2098ed2423d201f7/aapt-2.3.1.rc2.jar (No such file or directory)

### ISSUE THREAD

**Issue by BigBigDeBoy** [alibaba/atlas#195]
请按照下面的规则提交您的issue，符合标准的issue会被优先处理,
请先查看有没有同类型的issue已经存在.

1. demo问题的issue格式： [demo]:title

   title尽量反应问题的状况，如果是编译问题或者无法运行，正文写明是windows还是mac，如果是不清楚如何使用demo，请先查看https://github.com/alibaba/atlas/blob/master/atlas-demo/README.zh_cn.md
     
2. 容器功能接入或者如何使用的答疑：[use]:title
3. 提新需求的格式：[feature]:title

**Comment by BigBigDeBoy** [comment]
Applications/Android%20Studio.app/Contents/gradle/gradle-3.3/caches/modules-2/files-2.1/com.taobao.android/aapt/2.3.1.rc2/af3b8747854c5ca14dc9a7aa2098ed2423d201f7/aapt-2.3.1.rc2.jar (No such file or directory)

**Comment by CODEMPEROR** [comment]
同学，你解决这个问题了吗？

**Comment by hwjump** [comment]
工具和core对齐最新的release版本 一般都不会出问题。
