### ISSUE TITLE
[use]:aapt.exe'' finished with non-zero exit value -1073741819

### ISSUE THREAD

**Issue by walker0402** [alibaba/atlas#196]
容器功能接入按照文档并参考demo的配置，打包时有如下错误

Error:org.gradle.process.internal.ExecException: Process 'command 'C:\Users\walker\.gradle\caches\modules-2\files-2.1\com.taobao.android\aapt\2.3.1.rc2\af3b8747854c5ca14dc9a7aa2098ed2423d201f7\aapt-2.3.1.rc2\aapt.exe'' finished with non-zero exit value -1073741819

Error:Execution failed for task ':app:processResAwbsDebug'.
> process res exception

**Comment by hwjump** [comment]
往前看的出错提示，这一般资源冲突导致的

**Comment by hwjump** [comment]
升级atlas-core和atlas-plugin版本到最新的版本。要确保版本哈。最好全局搜下。因为有的地方可能写了个老版本
