### ISSUE TITLE
打tpatch补丁时，资源文件修改不生效

### ISSUE THREAD

**Issue by leidroid** [alibaba/atlas#197]
修改了java类，及布局xml文件，patch合并时，类能生效，xml文件修改的不生效，diff.json 文件中没看到R文件的修改描述，这是atlas版本没对齐的原因吗

**Comment by hwjump** [comment]
一般是这个原因。  老的版本我记得有这个bug。

**Comment by leidroid** [comment]
@hwjump 我拉了master的代码，demo运行也不行，也有这个问题啊。具体要对齐哪些版本后的

**Comment by hwjump** [comment]
classpath "com.taobao.android:atlasplugin:2.3.3.rc32"
