### ISSUE TITLE
[use] 打dexpatch生成的两个文件没有版本号

### ISSUE THREAD

**Issue by walker0402** [alibaba/atlas#200]
基于基线版本1.0.0，运行

**gradlew clean DexPatchPackageDebug -DapVersion=1.0.0**

output目录下生成**tpatch** 和**json**文件不带版本号
分别为

* @.tpatch
* dexpatch-.json

而不是

* 1.0.0@1.0.0.tpatch
* dexpatch-1.0.0.json

请问可能是什么原因造成的，AtalsDemo也是这样的

**Comment by lucky-chen** [comment]
打包命令更换了，文档已经更新，重新打包就好
