### ISSUE TITLE
关于bundle 跨项目问题

### ISSUE THREAD

**Issue by akingyin1987** [alibaba/atlas#203]
【问题】
 1、当前有个bundle 是项目A ，但项目B目前也要使用项目A 的bundle 引用过来后发现 引用过来的bundle 根本就没有打包成.so文件 放在APP里

//修改了引用后的路径
baseApFile project.rootProject.file('../tpsmp/app/build/outputs/ap

//bundle 引用的位置
project(":meterinfobundle").projectDir = file("../mrmseibundles/meterinfo

**Comment by hwjump** [comment]
项目B也要接入atlas打包插件，才可能打包成so放到app里面
