### ISSUE TITLE
[feature]:gradle4.0.1 buildtools:3.0.1该支持了

### ISSUE THREAD

**Issue by AnyMarvel** [alibaba/atlas#207]
gradle最新版本该支持了 现在在最新的as3.0.1上修改gradle版本好烦人

**Comment by AnyMarvel** [comment]
该问题可以关闭了。。看官网提示把gradle插件version指定去掉让他自动依赖就没问题了

**Comment by w1570187062** [comment]
老哥，咋整的？什么gradle插件的version？

**Comment by AnyMarvel** [comment]
atlas的core里面gradle插件依赖了适合他们的版本。在你的项目里面可以不用指定gradle的插件版本了。只用gradle就可以了

**Comment by xfront** [comment]
是能用，但都是旧的buildTool不能是26，用不了java8 lamba!!!!!!!!!!还是快升级真正支持3.0.1!!!

**Comment by lilongAAAA** [comment]
已经支持
