### ISSUE TITLE
bundle工程必须应用'maven-publish'插件？

### ISSUE THREAD

**Issue by xns1001** [alibaba/atlas#21]
我在自己编写demo时，建立的一个bundle项目仿照demo应用了'com.taobao.atlas.library'插件，编译报了个Task with name 'publish' not found in project ':bundlea'.
错误。但是加上“apply plugin: 'maven-publish”就好了。
问题来了，为什么bundle项目一定要maven-publish插件，难道bundle只能通过maven方式被host应用依赖吗？

**Comment by jiawulu** [comment]
是的， 该版本插件 对 bundle 的依赖 还不支持 compile project 的方式， 下个版本才能支持 。 至于 是否要用 maven-publish 取决你， 对 apk 来说只是需要一个依赖的坐标
