### ISSUE TITLE
[demo]:运行时报错

### ISSUE THREAD

**Issue by peterforme** [alibaba/atlas#217]
下载了demo，点击run就出现了报错
java.lang.ClassNotFoundException: Didn't find class "android.taobao.atlas.startup.AtlasBridgeApplication" on path: DexPathList[[zip file "/data/app/com.taobao.demo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.taobao.demo-2/lib/arm, /data/app/com.taobao.demo-2/base.apk!/lib/armeabi, /vendor/lib, /system/lib]]

**Comment by kylin17** [comment]
同问，请问后面如何解决的？

**Comment by peterforme** [comment]
@kylin17 不能直接点run  要在terminal里面输入命令来运行
