### ISSUE TITLE
dependencyTree-platformDevDebug.json 中 bundle 依赖未出现

### ISSUE THREAD

**Issue by huaf22** [alibaba/atlas#219]
在 mac os 系统上，atlas_core: 5.0.7.55, atlasplugin: 2.3.3.rc41，将本地编译成功的 bundle awb 上传到 maven 上，然后将app项目中的 bundleCompile project("marketing") 改成 bundle com.heli:marketing:7.29.0-atlas-SNAPSHOT, 调用 ./gradlew clean assembleDebug 编译出 apk， 发现 dependencyTree-platformDevDebug.json 中 marketing 模块中原先单独依赖的库没有了，编译出的 apk 运行在测试机上也报错  java.lang.NoClassDefFoundError，但是本地项目编译就会正常。

dependencyTree-platformDevDebug.json
`
{
    "awbs": {
        "com.heli:marketing:7.29.0-atlas-SNAPSHOT@awb": [
            "com.heli:viewcomponent:1.3.0@aar",
            "com.heli:pinyin:1.6@aar"
        ]
    },
    "mainDex": [
        "com.android.databinding:library:1.3.1@aar",
        "com.android.databinding:baseLibrary:2.3.3@jar",
        "com.android.support:support-annotations:26.0.1@jar",
        "com.android.support:support-compat:26.0.1@aar",
        "com.android.support:support-media-compat:26.0.1@aar"
    ]
}

`

**Comment by hwjump** [comment]
不要用flavor

https://github.com/alibaba/atlas/wiki/atlas%E6%8F%92%E4%BB%B6%E4%B8%8B%E6%9E%84%E5%BB%BA%E7%89%B9%E6%AE%8A%E5%8C%85%E7%9A%84%E6%AD%A3%E7%A1%AE%E5%A7%BF%E5%8A%BF

**Comment by huaf22** [comment]
最后解决了问题，bundleCompile 直接引用 maven 上库 transitive 默认为 false 的，所以只要用下面方式依赖就可以了
```
bundleCompile ("...") {
   transitive = true
}
```

**Comment by huaf22** [comment]
问题已解决 close
