### ISSUE TITLE
app接入科大讯飞广告后，点击进入bundle时，会打开主程序的activity，无法进入bundle的页面

### ISSUE THREAD

**Issue by oneapp1e** [alibaba/atlas#227]
跟踪断点截图如下
![image](https://user-images.githubusercontent.com/4979372/34549667-5f26acbc-f145-11e7-9339-094112a79a81.png)

![image](https://user-images.githubusercontent.com/4979372/34549653-3966b9fe-f145-11e7-822e-1f6a1758b579.png)
这个ClassLoader不是bundle的，主程序接入的有第三方广告

**Comment by oneapp1e** [comment]
补充，主程序接入的科大讯飞广告，会在项目的dada/dada/packetName/files/目录生成AdDex.3.0.11.dex文件，我把科大讯飞的广告去掉，AdDex.3.0.11.dex不会生成，那么bundle加载就成功了，如果广告存在就会走上面的截图流程造成无法进入bundle

**Comment by oneapp1e** [comment]
补充：反编译查看科大讯飞的源码
![image](https://user-images.githubusercontent.com/4979372/34554012-9eb602fe-f165-11e7-8098-d2f893f7685e.png)
填了好多坑，又进入了这一个坑。。。

**Comment by hwjump** [comment]
好吧。 atlas本身会去替换LoadApk里面的classloader，因为需要找到bundle中的类。 你这个case，可能需要写一段额外代码，建立讯飞的classloader和atlas的classloader的关系，然后最后替换为你的classloader。我暂时只想到这个方法。

**Comment by hwjump** [comment]
atlas加好了自保护代码。确保classloader不会被替换。
