### ISSUE TITLE
这是什么错误

### ISSUE THREAD

**Issue by cocohuQQ** [alibaba/atlas#23]
Execution failed for task ':prepareDebugAP'.
> Could not resolve all dependencies for configuration 'detachedConfiguration1'.
   > Could not find com.taobao.android.atlasdemo:AP-debug:1.0.0.
   Searched in the following locations:
         file:/Users/huai418/Documents/androidSDK/extras/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.pom
         file:/Users/huai418/Documents/androidSDK/extras/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.ap
         file:/Users/huai418/Documents/androidSDK/extras/google/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.pom
         file:/Users/huai418/Documents/androidSDK/extras/google/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.ap
         file:/Users/huai418/Documents/androidSDK/extras/android/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.pom
         file:/Users/huai418/Documents/androidSDK/extras/android/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.ap
         file:/Users/huai418/.m2/repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.pom
         file:/Users/huai418/.m2/repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.ap
         https://jcenter.bintray.com/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.pom
         https://jcenter.bintray.com/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.ap
     Required by:
         com.taobao.android.atlasdemo:app:1.0.1

**Comment by jiawulu** [comment]
需要先执行 buildApk， 把基线包 1.0 部署到本地仓库才行

**Comment by cocohuQQ** [comment]
已解决，谢谢

**Comment by victorfan336** [comment]
@cocohuQQ @jiawulu build apk是什么命令呀？我也报了这个错，我先执行了gradlew clean assembelDebug ，然后执行了gradlew publish发布，然后安装应用，最后修改对应版本号和文本内容后，执行gradlew clean assembleDebug -DapVersion=1.0.0 -DversionName=1.0.1的时候报上面的错误了，可以说具体点吗？谢谢
