### ISSUE TITLE
[demo]:RemoteView创建时RemoteFactory.requestRemote报：no match remote-item with intent错误（Mainifest已经注册了）

### ISSUE THREAD

**Issue by fushiming1983** [alibaba/atlas#230]
Mainifest：
<meta-data android:name="atlas.view.intent.action.SECOND_RICH1"
            android:value="com.taobao.secondbundle.MyRichFrameLayout"/>

User:
RemoteFactory.requestRemote(RemoteView.class, this, new Intent("atlas.view.intent.action.SECOND_RICH1"),
                new RemoteFactory.OnRemoteStateListener<RemoteView>() {
            @Override
            public void onRemotePrepared(RemoteView iRemoteContext) {
                FrameLayout layout = (FrameLayout) findViewById(R.id.fl_content);
                FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
                layout.addView(iRemoteContext,params);
            }

            @Override
            public void onFailed(String s) {
                Log.e("UserRemoteActivity",s);
            }
        });

打断点时查看：BundleListing.BundleInfo -> remoteViews 为空

**Comment by candledragle** [comment]
@fushiming1983 我也遇到了这个问题，我还测试了RemoteFragment

**Comment by sony9997** [comment]
我也遇到了

**Comment by 18311023368** [comment]
同问

**Comment by zhangfeifeilz** [comment]
将demo中的atlas的版本改为5.0.8.0-rc46@aar就可以了。貌似这个是demo中引用的那个版本的一个bug
