### ISSUE TITLE
 [demo]:同步失败 com.taobao.android:atlasplugin:2.3.3.rc41 Androidstudio3.0.1

### ISSUE THREAD

**Issue by maxinlei** [alibaba/atlas#231]
以下是控制台 报错

Error:(6, 0) Unable to load class 'org.gradle.api.internal.component.Usage'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by hwjump** [comment]
请使用gradle3.3的bin

**Comment by maxinlei** [comment]
我已经在 AtlasDemo 的 build.gradle dependencies 里面添加 
classpath 'com.android.tools.build:gradle:2.3.3'
但是 还是不好使 对应的就是 gradle3.3的bin
我的是 mac os

**Comment by hwjump** [comment]
有两个概念  com.android.tools.build:gradle:2.3.3 和 gradle的版本。 前面那个是google原生的android打包插件，它是基于gradle运行的。 atlas修改了原生的打包插件。所以只需要依赖atlasplugin就好了。 目前的atlasplugin是基于com.android.tools.build:gradle:2.3.3 改的。 它需要的gradle版本是3.3，你现在的错误是使用了4.0以上的gradle。

**Comment by maxinlei** [comment]
咱们会支持 com.android.tools.build:gradle:3.0.1  或以上 gradle4.1的bin 或以上吗 要是支持大约多久 能到 正式版

**Comment by hwjump** [comment]
会，在开发中
