### ISSUE TITLE
更新时报错：prepare client error

### ISSUE THREAD

**Issue by victorfan336** [alibaba/atlas#232]
之前所有的操作都正常，在生成了patch和json文件之后，推到手机上进行merge,在activity中调用 AtlasUpdater.update(info, patchFile);，报了如下错误 prepare client error，而且会卡会卡很久,导致ANR错误，具体报错如下:

07-06 18:33:32.000 9035-9035/com.xuebansoft.xinghuo.manager W/System.err: java.lang.RuntimeException: prepare client error
07-06 18:33:32.000 9035-9035/com.xuebansoft.xinghuo.manager W/System.err: at com.taobao.atlas.update.util.PatchMerger.getMergeClient(PatchMerger.java:210)
07-06 18:33:32.020 9035-9035/com.xuebansoft.xinghuo.manager W/System.err: at com.taobao.atlas.update.util.PatchMerger.merge(PatchMerger.java:106)
07-06 18:33:32.020 9035-9035/com.xuebansoft.xinghuo.manager W/System.err: at com.taobao.atlas.update.AtlasUpdater.update(AtlasUpdater.java:47)

希望知道的大大帮帮忙，谢谢

**Comment by hwjump** [comment]
异步调哈

**Comment by victorfan336** [comment]
@hwjump 谢谢回答，异步只是解决ANR问题，但是主要是报错“prepare client error”的问题，能给点提示吗？
