### ISSUE TITLE
[demo]:Task 'assemblePathDebug' not found in project

### ISSUE THREAD

**Issue by candledragle** [alibaba/atlas#234]
文档提供的步骤：

"1、安装设备且连接电脑成功\n\n" +
        "2、修改一个bundle工程的代码或者自由（设置生效的标识）\n\n" +
        "3、bundle工程的目录下执行 ../gradlew clean assemblePatchDebug,然后等应用重启或者应用关闭后点击重启"
测试结果：

* What went wrong:
Task 'assemblePathDebug' not found in project ':secondbundle'.

**Comment by hwjump** [comment]
https://github.com/alibaba/atlas/blob/master/atlas-demo/AtlasDemo/Tpatch.txt

**Comment by hwjump** [comment]
另外assemblePatchDebug task已经合并了。都用的 是assembleDebug。 通过版本号来区分是dexpatch打包还是动态部署打包
