### ISSUE TITLE
java.io.FileNotFoundException: bundleInfo-1.0.0.json

### ISSUE THREAD

**Issue by williamsim** [alibaba/atlas#248]
集成报了这个错，是什么配置没对吗？
System.err: java.io.FileNotFoundException: bundleInfo-1.0.0.json

System.err:     at android.content.res.AssetManager.openAsset(Native Method)
System.err:     at android.content.res.AssetManager.open(AssetManager.java:329)
System.err:     at android.content.res.AssetManager.open(AssetManager.java:303)
System.err:     at android.taobao.atlas.bundleInfo.AtlasBundleInfoManager.getFromAssets(AtlasBundleInfoManager.java:480)
System.err:     at android.taobao.atlas.bundleInfo.AtlasBundleInfoManager.updateBundleListingWithExtraInfo(AtlasBundleInfoManager.java:435)
System.err:     at android.taobao.atlas.bundleInfo.AtlasBundleInfoManager.<init>(AtlasBundleInfoManager.java:286)
System.err:     at android.taobao.atlas.bundleInfo.AtlasBundleInfoManager.instance(AtlasBundleInfoManager.java:250)
System.err:     at android.taobao.atlas.runtime.BundleUtil.checkBundleStateSyncOnUIThread(BundleUtil.java:235)
System.err:     at android.taobao.atlas.runtime.DelegateClassLoader.findClass(DelegateClassLoader.java:257)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
System.err:     at android.taobao.atlas.runtime.DelegateClassLoader.loadClass(DelegateClassLoader.java:248)
System.err:     at android.app.ActivityThread.installProvider(ActivityThread.java:5383)
System.err:     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4968)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at android.taobao.atlas.hack.Hack$HackedMethod.invoke(Hack.java:393)
System.err:     at android.taobao.atlas.bridge.BridgeApplicationDelegate.onCreate(BridgeApplicationDelegate.java:485)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at android.taobao.atlas.startup.AtlasBridgeApplication.onCreate(AtlasBridgeApplication.java:362)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
System.err:     at android.taobao.atlas.runtime.InstrumentationHook.callApplicationOnCreate(InstrumentationHook.java:1064)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4927)
System.err:     at android.app.ActivityThread.-wrap1(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1534)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:111)
System.err:     at android.os.Looper.loop(Looper.java:207)

**Comment by huaf22** [comment]
这个被catch了, 只是报错, 不crash吧

**Comment by hwjump** [comment]
原则上 打包会把bundleinfo-版本号.json 放到assert目录，你自己可以检查一下打出来的apk文件。 如果没有，不影响使用，但是一些强校验信息以及远程bundle会受影响
