### ISSUE TITLE
[demo]:databinding不能使用在remote bundle中

### ISSUE THREAD

**Issue by kymjs** [alibaba/atlas#250]
复现步骤： 
1. clone AtlasDemo (master分支与dev分支均会出现)    
2. 只改动`app/build.gradle`这里（如下图）

``` 
atlas{
    tBuildConfig{
        //将原本打在包内的 databindbundle 声明为 outOfApkBundle   
        outOfApkBundles = ['databindbundle']
    }
}
```

![image](https://user-images.githubusercontent.com/5780230/37135431-4ae28bda-22d8-11e8-8102-d1f7cd52336b.png)

3. 重新 run demo，并下发生成的`libcom_taobao_databindbundle.so`文件
4. 点击Demo侧滑菜单的databindbundle菜单项，则复现

异常内容：   
![image](https://user-images.githubusercontent.com/5780230/37135564-c32736f4-22d8-11e8-9185-659993176682.png)

**Comment by kymjs** [comment]
翻了一下历史issue，跟 #177 应该是同一个原因。

**Comment by hwjump** [comment]
https://github.com/alibaba/atlas/commit/2ce1a0842e3cc3bb13823bbb75cf34162d695f21

**Comment by hwjump** [comment]
这次提交里修复了，还没有发新版。  用atlas-core  5.8.0.1-rc1这个版本以上
