### ISSUE TITLE
[use]:vivo X9安装后出来一个附属应用和升级到android7.1.2时安装提示解析软件包错误，但是在三星和华为上是好的

### ISSUE THREAD

**Issue by zhangfeifeilz** [alibaba/atlas#257]
在vivo x9 funtouchos _3.0时能安装但是在桌面会多出来一个附属应用的启动图标，点进去完全一样，然后升级手机系统到3.1，android为7.1.2时，安装的时候直接提示解析软件包错误，但是在三星和华为等的手机上是好的，不知道这一块是不是兼容引起的，有什么解决办法，谢谢！！！

**Comment by hwjump** [comment]
这个听起来是 系统问题啊。   解析包出错，一个可能是包不完整，一个可能是AndroidManifest里面的内容刚好某一块这个系统不兼容。建议在这些方面排查一下。
