### ISSUE TITLE
./gradlew clean assembleDebug -DapVersion=1.0.0 -DversionName=1.0.1执行出问题

### ISSUE THREAD

**Issue by mowenjianmowenjian** [alibaba/atlas#26]
我在执行这句话./gradlew clean assembleDebug -DapVersion=1.0.0 -DversionName=1.0.1
会包下面这个错
![qq 20170314171842](https://cloud.githubusercontent.com/assets/20806095/23893688/6d0f413a-08da-11e7-94c3-4071a1e42076.png)

**Comment by mowenjianmowenjian** [comment]
![qq 20170314172357](https://cloud.githubusercontent.com/assets/20806095/23893856/0734b920-08db-11e7-9b7f-b1eb03baf6a4.png)

**Comment by wlianghe00** [comment]
文件被占用？studio都退了再进去运行试试

**Comment by mowenjianmowenjian** [comment]
不行，还是不行。
我是window下，1.8jdk尝试的不行。
电脑重启也不行
重新下载项目解压尝试也不行

**Comment by xunyixiangchao** [comment]
![image](https://cloud.githubusercontent.com/assets/7007625/23930204/c0285952-0965-11e7-804b-1734b5960bc9.png)
![image](https://cloud.githubusercontent.com/assets/7007625/23930212/c7945a7e-0965-11e7-9b5a-22095ae607e4.png)
这个patchs.json,就是文档里的update.json吧？
