### ISSUE TITLE
dexinterpret.so 和dalvikhack.so会开源么

### ISSUE THREAD

**Issue by liumengdeqq** [alibaba/atlas#268]

**Comment by hwjump** [comment]
请参考前面某个issue的回答。

**Comment by xingda920813** [comment]
懒人包: https://github.com/alibaba/atlas/issues/161

houliang commented on 19 Jul 2017
请问下dexinterpret\dalvikhack\dalvikpatch几个so里面的代码能开源吗？

hwjump commented on 4 Aug 2017
暂时没有计划。
