### ISSUE TITLE
java.io.FileNotFoundException 

### ISSUE THREAD

**Issue by johnx4** [alibaba/atlas#27]
xxxxxxxxx\build\intermediates\multi-dex\debug\manifest_keep.txt (系统找不到指定的文件。)

**Comment by johnx4** [comment]
无法生成manifest_keep.txt

**Comment by jiawulu** [comment]
deno里的例子吗？ 有做过代码修改没？

**Comment by johnx4** [comment]
不是demo里的例子,是应用在目前的项目工程中，应该不需要引入multidex的包也不需要这样调用 MultiDex.install(context)吧？

**Comment by jiawulu** [comment]
Atlas 会做multidex install 的逻辑的， 自己的工程注意下 几个版本，参考demo：

atlasplugin ： 2.2.3.rc+
android builder ： 2.2.3
android tools ： 23，24
gradle ： 2.14.1
jdk ： 1.8

**Comment by johnx4** [comment]
目前还是无法生成。。。。。。。
