### ISSUE TITLE
[use]:能不能给一个升级到gradle plugin3.0.1的demo

### ISSUE THREAD

**Issue by cumtkangyi** [alibaba/atlas#270]
dependencies {
//        classpath 'com.android.tools.build:gradle:2.2.0'
        classpath "com.taobao.android:atlasplugin:3.0.1-rc58"
    }

由于项目需要，目前需要升级到gradle plugin3.0.1，现有的demo看不出是支持3.0.1,能不能给一个升级到gradle plugin3.0.1插件的demo配置

**Comment by hwjump** [comment]
gradle_4.0.1 分支
