### ISSUE TITLE
[demo]:为何用startActivity也可以直接打开SecondBundleActivity

### ISSUE THREAD

**Issue by 08carmelo** [alibaba/atlas#283]
demo中在MainActivity打开SecondBundleActivity的方式是
`switchToActivity("second","com.taobao.secondbundle.SecondBundleActivity");`
因为SecondBundle没有加载，所以必须先加载bundle，在跳转。

但是我把这句代码改成：
`Intent intent = new Intent();                        intent.setClassName(MainActivity.this,"com.taobao.secondbundle.SecondBundleActivity");
                        startActivity(intent);`
为何也可以呢？ 区别在哪

**Comment by 08carmelo** [comment]
@hwjump

**Comment by hwjump** [comment]
switchToActivity使用ActivityGroup的形式将SecondBundleActivity的View加载到一个Activity中。
startActivity就是拉起了真正的SecondBundleActivity。

两者都要去安装bundle

**Comment by 08carmelo** [comment]
原因是你们hook了startActivity，才发现
