### ISSUE TITLE
[use]:生成动态部署包时报异常

### ISSUE THREAD

**Issue by yunsimon** [alibaba/atlas#290]
执行“gradlew clean assembleRelease -DapVersion= -DversionName=“生成动态部署包时报异常：
java.util.concurrent.ExecutionException: org.jf.util.ExceptionWithContext: Multiple definitions for method XXX

实际看基准包mapping文件，并没有重复定义该方法

请问知道是什么原因吗？

**Comment by hwjump** [comment]
请再仔细看下，基本上肯定是重复了。 或者你把cache清一下。
