### ISSUE TITLE
执行buildTpatch.sh报错

### ISSUE THREAD

**Issue by hzd2712** [alibaba/atlas#30]
日志是这样的：

* What went wrong:
Execution failed for task ':atlas-demo:app:prepareDebugAP'.
> Could not resolve all dependencies for configuration 'detachedConfiguration1'.
   > Could not find com.taobao.android.atlasdemo:AP-debug:1.0.0.
     Searched in the following locations:
         file:.../android-sdk-macosx/extras/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.pom
         file:.../android-sdk-macosx/extras/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.ap
         file:.../android-sdk-macosx/extras/google/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.pom
         file:.../android-sdk-macosx/extras/google/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.ap
         file:.../android-sdk-macosx/extras/android/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.pom
         file:.../android-sdk-macosx/extras/android/m2repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.ap
         file:.../.m2/repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.pom
         file:.../.m2/repository/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.ap
         https://jcenter.bintray.com/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.pom
         https://jcenter.bintray.com/com/taobao/android/atlasdemo/AP-debug/1.0.0/AP-debug-1.0.0.ap
     Required by:
         com.taobao.android.atlasdemo:app:1.0.1

**Comment by jiawulu** [comment]
https://github.com/alibaba/atlas/issues/23#issuecomment-286371194
