### ISSUE TITLE
[use]一个基线版本的一个bundle可以产生多个DexPatch，而且名字是一样的，服务端怎么维护这些DexPatch呢

### ISSUE THREAD

**Issue by iyezhou** [alibaba/atlas#304]
DexPatch名字都一样
1、同一个bundle的不同DexPatch怎么区别
2、不同bubdle的DexPatch怎么区别

**Comment by hwjump** [comment]
很简单，dexpatch有版本的概念不就可以维护了

**Comment by iyezhou** [comment]
@hwjump 那dexpatch文件名需要自己手动改一下吗，以区分不同版本及不同bundle

**Comment by hwjump** [comment]
这个自己服务端实现。 不发表意见

**Comment by iyezhou** [comment]
@hwjump 今天把服务端开发完了，哈哈

**Comment by ccwant** [comment]
> @hwjump 今天把服务端开发完了，哈哈

你好，能分享一下思路么？=同一个版本第二次DexPatch到底该怎么操作才能成功?
