### ISSUE TITLE
[use]插件都是以32位加载so动态链接库的吗

### ISSUE THREAD

**Issue by iyezhou** [alibaba/atlas#309]
我在插件里放了arm64-v8a、armeabi、armeabi-v7a、x86等版本的so，但还是报
```
lib/libxxx.so" is 32-bit instead of 64-bit
```
说明app以64位运行，然后在插件中却加载了32位的so库导致报错

**Comment by hwjump** [comment]
你要配置一个开关，将所有bundle打到assert下。 看下打包插件代码。  这样就不会导致bundle的apk产物被认为是so。

**Comment by iyezhou** [comment]
@hwjump 是什么配置呢

**Comment by hwjump** [comment]
atlas.tBuildConfig.keepInLibSoNames=null
