### ISSUE TITLE
Android P libdexinterpret.so失效

### ISSUE THREAD

**Issue by lizhangqu** [alibaba/atlas#317]
在Android P上调用
com.taobao.android.dex.interpret.ARTUtils.init(context);
Boolean result = com.taobao.android.dex.interpret.ARTUtils.setIsDex2oatEnabled(false);

result返回false，禁用dex2oat失败

另外能否将libdexinterpret.so的源码开源一下？

**Comment by DeanKersting** [comment]
开源不彻底 真的有点烦，这个也不是啥宝贝东西

**Comment by JasMSS** [comment]
能否出个教程，讲解大致思路 @addhaloka  让我等膜拜一下
