### ISSUE TITLE
找不到依赖包Could not resolve dom4j:dom4j:2.0.

### ISSUE THREAD

**Issue by shantong** [alibaba/atlas#32]
Error:A problem occurred configuring root project 'app'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve dom4j:dom4j:2.0.
     Required by:
         :app:unspecified > com.taobao.android:atlasplugin:2.2.3.rc2
      > Could not resolve dom4j:dom4j:2.0.
         > Could not get resource 'https://jcenter.bintray.com/dom4j/dom4j/2.0/dom4j-2.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/dom4j/dom4j/2.0/dom4j-2.0.pom'.
               > jcenter.bintray.com

**Comment by xunyixiangchao** [comment]
更新一下用新的就好了。有改动

**Comment by shantong** [comment]
更新啥，demo更新下，还是dom4j，我看中央仓库上dom4j只有1.6的

**Comment by xunyixiangchao** [comment]
demo更新下

**Comment by shantong** [comment]
更新了，java版本要用1.8吗，有交流群某

**Comment by jiawulu** [comment]
https://github.com/alibaba/atlas/issues/34
