### ISSUE TITLE
atlasplugin:3.0.1-rc71-3 Report the following questions

### ISSUE THREAD

**Issue by huohu1007** [alibaba/atlas#320]
Gradle sync failed: More than one variant of project :paycenter matches the consumer attributes:
			- Configuration ':paycenter:debugApiElements' variant android-aidl:
			- Found artifactType 'android-aidl' but wasn't required.
			- Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
			- Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
			- Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
			- Required org.gradle.api.attributes.Usage 'java-api' and found compatible value 'java-api'.
			- Configuration ':paycenter:debugApiElements' variant android-classes:
			- Found artifactType 'android-classes' but wasn't required.
			- Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
			- Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found comp... (show balloon)

**Comment by hwjump** [comment]
自己工程配置文件看下，这里说的是有些东西重复。

**Comment by lilongAAAA** [comment]
如果你是本地多project的相互依赖，请在根目录的build.gradle添加：
allprojects {
.......
configurations {
compileProject.extendsFrom compile, archives
}
}

**Comment by Huyamin150** [comment]
@lilongAAAA 按照你这样做的话，项目中app的资源就无法依赖到library里面资源了，请问有设么办法么
