### ISSUE TITLE
[use]:Android P支持动态部署吗？

### ISSUE THREAD

**Issue by pangzhen** [alibaba/atlas#323]
华为 Android P 使用动态部署后出现：
Fatal Exception: java.lang.InternalError
Attempt to register dex file /system/framework/org.apache.http.legacy.boot.jar with multiple class loaders

atlas_core: 5.1.0.8-RC1
atlas-update: 1.1.4.22-rc7
atlas-plugin: 3.0.1-rc81
features:

4.dexpatch and dynamic deployment support android P below

最新版本的atlas也是在Android P 以下才能生效？

**Comment by hwjump** [comment]
不支持。 动态部署在P上的跨dex inline校验会出问题，atlas整包在P上是能工作的
