### ISSUE TITLE
项目怎么克隆不下了啊

### ISSUE THREAD

**Issue by ShuaiXiu** [alibaba/atlas#324]
请按照下面的规则提交您的issue，符合标准的issue会被优先处理,
请先查看有没有同类型的issue已经存在.

1. demo问题的issue格式： [demo]:title

   title尽量反应问题的状况，如果是编译问题或者无法运行，正文写明是windows还是mac，如果是不清楚如何使用demo，请先查看https://github.com/alibaba/atlas/blob/master/atlas-demo/README.zh_cn.md
     
2. 容器功能接入或者如何使用的答疑：[use]:title
3. 提新需求的格式：[feature]:title

**Comment by hwjump** [comment]
...

**Comment by ShuaiXiu** [comment]
老哥能克隆吗？能克隆发我邮箱一份，万分感谢。

**Comment by ShuaiXiu** [comment]
131927276@qq.com

**Comment by hwjump** [comment]
git工具和网络检查下。    就算不会git，github页面也有个download按钮，按一下

**Comment by ShuaiXiu** [comment]
在github里面下载网速很慢，下载几分钟后就会0KB，然后下载失败，用git客户端下载出现RPC failed; curl 18 transfer closed with outstanding read data remaining，用AS克隆出现SSL错误，百度了没找到好方法

**Comment by hwjump** [comment]
翻墙

**Comment by ShuaiXiu** [comment]
老哥克隆发我邮箱一份啊  万分感谢了
