### ISSUE TITLE
[use]项目编译能通过，运行报build文件中有个atlas代理文件(Atlas_proxy_包名_android_provider.java)找不到

### ISSUE THREAD

**Issue by huihuishoumei** [alibaba/atlas#334]
具体log日志如下
Caused by: java.lang.IllegalArgumentException: Unable to find source java class: 'D:\project\seller\app\build\generated\source\atlasproxy\debug\android\taobao\atlas\runtime\newcomponent\ATLASPROXY_com_DHgate_seller_android_Provider.jav
a' because it does not belong to any of the source dirs: '[
D:\project\seller\app\src\main\java,
D:\project\seller\app\src\debug\java, 
D:\project\seller\app\build\generated\source\r\debug, D:\project\seller\app\build\generated\source\buildConfig\debug, D:\project\seller\app\build\generated\source\aidl\debug, D:\project\seller\app\build\generated\source\rs\debug, D:\project\seller\app\build\generated\source\atlascore\debug]'

我仔细查了一下，是因为它没有搜索atlasproxy目录，各位大哥哥大姐姐，帮忙看看为什么

**Comment by hwjump** [comment]
这是因为 这个类是 打包插入的。   出这个的原因一般是 atlas-plugin和 atlas-core 匹配导致的
