### ISSUE TITLE
App工程里面的UpdateInfo字段和生成的的patchs.json里面的字段不一样也？

### ISSUE THREAD

**Issue by loveskill** [alibaba/atlas#35]
这个是patchs.json文件：`{
    "baseVersion": "1.0.0",
    "diffBundleDex": true,
    "patches": [
        {
            "bundles": [
                {
                    "applicationName": "com.taobao.firstbundle.FirstBundleApplication",
                    "artifactId": "firstbundle",
                    "dependency": [],
                    "mainBundle": false,
                    "newBundle": false,
                    "pkgName": "com.taobao.firstbundle",
                    "version": "1.0.1"
                },
                {
                    "applicationName": "android.taobao.atlas.startup.AtlasBridgeApplication",
                    "mainBundle": true,
                    "name": "libcom_taobao_maindex",
                    "newBundle": false,
                    "pkgName": "com.taobao.demo",
                    "version": "1.0.1"
                }
            ],
            "fileName": "patch-1.0.1@1.0.0.tpatch",
            "patchVersion": "1.0.1",
            "targetVersion": "1.0.0"
        }
    ]
}`

然后UpdateInfo类是这样的：
` /**
     * 当前的客户端版本
     */
    public String baseVersion;
    /**
     * 更新后的客户端版本
     */
    public String updateVersion;

    /**
     * 更新的模块列表信息
     */
    public List<Item> updateBundles;

    public File workDir = new File(RuntimeVariables.androidApplication.getCacheDir(), "atlas_update");

public class UpdateInfo implements Serializable{

    /**
     * 当前的客户端版本
     */
    public String baseVersion;
    /**
     * 更新后的客户端版本
     */
    public String updateVersion;

    /**
     * 更新的模块列表信息
     */
    public List<Item> updateBundles;

    public File workDir = new File(RuntimeVariables.androidApplication.getCacheDir(), "atlas_update");

    /**
     * 更新的模块信息
     */
    public static class Item implements Serializable {
        /**
         * 是不是主dex
         */
        public boolean isMainDex;
        /**
         * bundle 的名称
         */
        public String name;
        /**
         * bundle 版本信息
         */
        public String version;
        /**
         * bundle 的代码仓库对应的版本
         */
        public String srcVersion;
        /**
         * 依赖的 bundle 列表
         */
        public List<String> dependency;
    }

}`

**Comment by lilongAAAA** [comment]
代码真正用的是update.json,patchs.json可以做动态部署测试使用
