### ISSUE TITLE
[use]:jar包中的assets文件没有被打包进apk

### ISSUE THREAD

**Issue by pangzhen** [alibaba/atlas#350]
使用atlas-plugin: 3.0.1-rc81打包，引用的jar包里面有assets文件夹，但里面的文件没有被打包进apk，打包工程目录下的assets文件有被打包进apk

**Comment by hwjump** [comment]
jar包的assets本来就不是标准做法。 请转成aar吧。

**Comment by joyruby** [comment]
咋给关了？ 我也遇到同样的问题了。而且我去掉atlas之后 是可以打包进去的。
虽然不规范，但还是希望能像标准的android tools一样给一下兼容。

谢谢哈！

**Comment by pangzhen** [comment]
> 咋给关了？ 我也遇到同样的问题了。而且我去掉atlas之后 是可以打包进去的。
> 虽然不规范，但还是希望能像标准的android tools一样给一下兼容。
> 
> 谢谢哈！

自己改了 https://github.com/pangzhen/atlas-fixP

**Comment by hzl123456** [comment]
> > 咋给关了？ 我也遇到同样的问题了。而且我去掉atlas之后 是可以打包进去的。
> > 虽然不规范，但还是希望能像标准的android tools一样给一下兼容。
> > 谢谢哈！
> 
> 自己改了 https://github.com/pangzhen/atlas-fixP

jar包中的asset文件打包进apk，这块该怎么实现呢
