### ISSUE TITLE
[use]:开启混淆报空指针异常

### ISSUE THREAD

**Issue by iDev01** [alibaba/atlas#357]
master分支最新代码
atlas-gradle-plugin的com.taobao.android.builder.tasks.transform.AtlasProguardTransform.java中，成员变量configList未初始化就直接使用，报空指针异常。

**Comment by joyruby** [comment]
@iDev01 我也遇到了同样的问题，请解决了吗？

**Comment by joyruby** [comment]
改成3.0.1-rc81的版本，成功编译

**Comment by iDev01** [comment]
最新代码变量初始化一下也能改成能编译的，但是不知道原意怕出错，所以想请作者修复一下。

**Comment by iDev01** [comment]
[最新更新](https://github.com/alibaba/atlas/commit/94a206e6ddfcf5d820e67dfd185d81ee9489ac7a)
