### ISSUE TITLE
Android Q NoSuchMethodException

### ISSUE THREAD

**Issue by tangkai** [alibaba/atlas#361]
[Android Q NoSuchMethodException]:title

执行下面代码出现错误，
```java
 NonConfigurationInstances = Hack.into("android.app.Activity$NonConfigurationInstances");
ActivityThread_startActivityNow = AtlasHacks.ActivityThread.method("startActivityNow",Activity.class,String.class,
                Intent.class,ActivityInfo.class, IBinder.class,Bundle.class,NonConfigurationInstances.getmClass());

```
错误日志
java.lang.NoSuchMethodException: android.app.ActivityThread.startActivityNow [class android.app.Activity, class java.lang.String, class android.content.Intent, class android.content.pm.ActivityInfo, interface android.os.IBinder, class android.os.Bundle, class android.app.Activity$NonConfigurationInstances]

**Comment by lilongAAAA** [comment]
不要在依赖activitygroupcompat，在主dex可直接使用localActivityManager去startActivity
