### ISSUE TITLE
Error:Could not find dom4j:dom4j:2.0.

### ISSUE THREAD

**Issue by xns1001** [alibaba/atlas#4]
demo里的app和Firstbundle编译时找不到2.0版本的dom4j
![image](https://cloud.githubusercontent.com/assets/15882710/23843991/6482a308-07fa-11e7-94b3-62851b5f443d.png)
jcenter上没有这个版本的dom4j

**Comment by beansoftapp** [comment]
http://central.maven.org/maven2/dom4j/dom4j/ here the latest version is: 1.6.1, where to find doj4j 2.0?

**Comment by lilongAAAA** [comment]
正在更新，请稍等

**Comment by jiawulu** [comment]
已经修复，同时插件升级到 2.2.3.rc4  版本

**Comment by 401885064** [comment]
晕，原来这样。。。 我就郁闷了  ，怎么官方demo都跑不通。。。。

**Comment by cxMax** [comment]
demo插件版本com.taobao.android:atlasplugin:2.3.3.rc1 会编译不过, "Could not find method implementation() for arguments [directory 'libs']"
用com.taobao.android:atlasplugin:2.3.1.rc9就ok了
