### ISSUE TITLE
支持加固吗

### ISSUE THREAD

**Issue by north2016** [alibaba/atlas#40]
如果使用组件化，被＊＊＊应用市场给强制加固，会不会对Atlas有影响

**Comment by fengxueren** [comment]
目前没发现有影响，如果应用市场改动了dex文件，可能需要dex文件做基线包生成patch

**Comment by wuuchao** [comment]
@fengxueren 需要dex文件做基线包生成patch。能不能有一个具体操作的描述

**Comment by zjutyujf** [comment]
请参考demo，左侧nativegationdraw里面有先关patch的说明
