### ISSUE TITLE
你们这个DEMO简直就是给8年+的人看的

### ISSUE THREAD

**Issue by Huyamin150** [alibaba/atlas#41]
altas的大神们，能否在开源之后对于demo和上手指导方面照顾一下我们普通的程序员，真的是无法看懂，不是一开始issue里链接了一个简书，我可能完全无法知道怎样去搭建项目，上手指南讲述的跟原理一样，还请在demo功能上以及doc的概述上尽可能的丰富一些。

**Comment by benshayu2015** [comment]
你看不懂就对了，人家就是让你看不懂，不然点击率怎么上去呢

**Comment by yangb1993** [comment]
哈哈，有学习才有进步嘛

**Comment by Huyamin150** [comment]
@benshayu2015 通过凑issue的人气么 ……

**Comment by xns1001** [comment]
阿里这次的开源确实没做好，本来atlas就非常复杂，文档和demo还这么差。

**Comment by eatdefecat** [comment]
这里有说明 http://www.jianshu.com/p/f1f471f98d08

**Comment by zzzzzzkang** [comment]
你们不报错么，Error:Could not find dom4j:dom4j:2.0.

**Comment by zhaolei9527** [comment]
看不懂的+1

**Comment by zjutyujf** [comment]
新的demo已经上线，有问题再沟通
