### ISSUE TITLE
buildApk.sh构建错误

### ISSUE THREAD

**Issue by maolubin** [alibaba/atlas#44]
_我构建完了后，跑通后，又修改了下firstbundle加了个activity，想更新以前的，然后再去调buildApk.sh，就报下面的错误了，是不能覆盖吗？

![qq 20170316180128](https://cloud.githubusercontent.com/assets/18607571/23991022/d5198abc-0a72-11e7-9d15-d86c8f96ce1f.png)

**Comment by jiawulu** [comment]
抱歉  由于大小写的问题给你造成困扰了 。 

最好还是自己加一个awb 模块进来，先做apk 构建， 然后修改 awb 模块， 升级版本号，做patch 构建

**Comment by jiawulu** [comment]
更新，用最新demo
