### ISSUE TITLE
开源诚意不够啊！

### ISSUE THREAD

**Issue by Gmle7** [alibaba/atlas#48]
对入门者不友好，没得至少两年经验估计是搞不定的

**Comment by yangb1993** [comment]
尤小优有一句话叫，凭什么牺牲自己陪老婆和孩子的时间来做这些。所以要自己学不要埋怨

**Comment by Gmle7** [comment]
你这是什么理论？能用在这里吗？写好README不是他们应该做的吗？既然开源就是想让更多人来学习，让他改一改，适合更多人一些，难道不是我们这些用开源的人应该做的吗？开源了就是要大家一起让项目更好，而不是就停在这里！请让开源更有意义

**Comment by fengxueren** [comment]
入门文档，demo在重新写 @Gmle7

**Comment by zjutyujf** [comment]
就这几天会上线新的demo

**Comment by K1Soo** [comment]
http://atlas.taobao.org/docs/
这里面都有解释的。

**Comment by 84hero** [comment]
以前就听说阿里内部技术等级晋升好像得有开源项目作为考评之一

**Comment by JacksonTian** [comment]
要是搞开源就能晋升的话我早就是总监了。

做来源 做得好还是不好 可以好好讨论，别整那些子虚乌有的阴谋论

发自我的 iPhone

**Comment by xiaolongren** [comment]
我看了文档也是不会用，project下的gradle怎么配置？app下的gradle怎么配置？bundleapp的gradle怎么配置？文档中没区分，直接一个garadle配置，配置哪里呢？

**Comment by zjutyujf** [comment]
可以参考最新的demo
