### ISSUE TITLE
[feature]:bundle的R类字段非final

### ISSUE THREAD

**Issue by xns1001** [alibaba/atlas#49]
我反编译发现bundle的R文件的所有字段都是非final的，这样不能替换为常量会对性能有影响吧？我看手淘里bundle的R里面的字段都是static final的。

**Comment by JiangDaYa0** [comment]
可以自己写gradle plugin替换掉

**Comment by jiawulu** [comment]
你的插件不是最新的把， 拉取下最新的代码

tBuildConfig.aaptConstantId 会来控制这个是否是final的， 纠正下手淘里用的都是非final的， 开源插件默认是final的。

具体可以看一下extension  对象 ， com.taobao.android.builder.extension.TBuildConfig

**Comment by xns1001** [comment]
我看看代码,谢谢
