### ISSUE TITLE
gradle插件的版本

### ISSUE THREAD

**Issue by chenenyu** [alibaba/atlas#5]
目前默认是Android gradle plugin version 是2.1，是否可以自己指定版本号？ 比如官方的apt在2.2才支持。 如果不支持，什么时候会更新呢？

**Comment by jiawulu** [comment]
2.2.3 版本源码这个礼拜会集成进来，jcenter 已经发了 2.2.3.rc3

**Comment by jiawulu** [comment]
已更新
