### ISSUE TITLE
[demo]:bundle如何调用宿主app里面的公共方法？

### ISSUE THREAD

**Issue by fuxiuyuan** [alibaba/atlas#50]
如题，还有，bundle A如何调用bundle B的方法？

**Comment by fengxueren** [comment]
宿主APP里的方法可以直接调用
Bundle 之间调用一般只支持四大组件的调用，如果是方法的公用，可以通过bundle之间依赖来实现。

**Comment by fuxiuyuan** [comment]
@fengxueren 怎么直接调用宿主APP里的方法？demo里面也没有示例呀，bundle的build.gradle要怎么写？否则怎么编译通过？

**Comment by zjutyujf** [comment]
宿主app里面的方法可以直接调用，比如说support v4 被打在宿主app里面，bundle可以直接在build.gradle中配置对support v4的依赖，正常编写代码即可，打包的时候回仲裁降v4包打入宿主，同时运行时容器完成对宿主类的查找

**Comment by zjutyujf** [comment]
下周二上线新版demo，增加对容器的接入理解，敬请期待

**Comment by JiangDaYa0** [comment]
@zjutyujf 坐等demo上线

**Comment by zjutyujf** [comment]
新demo可以体验起来
