### ISSUE TITLE
运行demo，点击动态部署后提示“更新失败，bundle input is wrong”不知道是为什么，生成的update.json 和新的patch

### ISSUE THREAD

**Issue by clgg** [alibaba/atlas#52]
{
	"baseVersion":"1.0.0",
	"updateBundles":[
		{
			"dependency":[],
			"isMainDex":false,
			"name":"com.taobao.firstbundle",
			"version":"1.0.0@1.0.1"
		},
		{
			"isMainDex":true,
			"name":"com.taobao.maindex",
			"version":"1.0.0@1.0.1"
		}
	],
	"updateVersion":"1.0.1"
}
update.json

patch-1.0.1@1.0.0.tpatch  这个是改了下firstbundle后 ，再一次构建产生的，fristbundle中只是改了文本，和版本号

**Comment by xiezhouhuang** [comment]
好像刚更新了这个问题, 把atlasupdate  版本1.1.4.2 改为1.1.4.3  就可以,可

**Comment by clgg** [comment]
果然是那个的问题，谢谢啊

**Comment by clgg** [comment]
更新失败，bundle input is wrong   可能是 tlasupdate 版本问题，1.1.4.2 改为1.1.4.3 就好了
