### ISSUE TITLE
[demo]动态部署问题

### ISSUE THREAD

**Issue by renyihui** [alibaba/atlas#55]
更新失败，bundle input is wrong

**Comment by renyihui** [comment]
bundleFilePath[index] = new File(bundlePair.first);
            if (!bundleFilePath[index].exists()) {
                throw new BundleException("bundle input is wrong");
            }
这个bundleFilePath[index]，不知道是第几次循环的时候不存在了，为什么啊

**Comment by xiezhouhuang** [comment]
https://github.com/alibaba/atlas/issues/52   版本问题,这个问题已经有人问过了

**Comment by renyihui** [comment]
@xiezhouhuang 谢谢，我当时没看见有人提这个问题

**Comment by xiezhouhuang** [comment]
@renyihui 不用, 看了新版的更新,应该是读取so顺序的问题
