### ISSUE TITLE
[feature]:为什么不支持 abiFilters "armeabi-v7a"的so打包

### ISSUE THREAD

**Issue by lixlee** [alibaba/atlas#56]
**atlas什么时候支持 armeabi-v7a中的so打包，这个应该很简单吧？我的应用只保留了 armeabi-v7a的so，尤其是一些三方的依赖的aar中也只提供 armeabi-v7a，要改回armeabi这个第三方的aar都得重新提供包，这个也太麻烦吧**

```
        ndk {
            abiFilters "armeabi-v7a"
        }
```
atlas的so都没有打进包中，导致无法运行，armeabi-v7a是常用的架构应该提供支持吧

**Comment by zjutyujf** [comment]
支持armeabi-v7a 支持的，只是so会走解压的形式安装

**Comment by lixlee** [comment]
我的意思是：
ndk {
   abiFilters "armeabi-v7a"
}
会导致atlas本身的so没有打进apk包中，导致启动的时候检查到安装包不完整

**Comment by jiqimaogou** [comment]
已收到反馈，马上处理。

**Comment by jiqimaogou** [comment]
com.taobao.android:atlas_core:5.0.6-rc26@aar 这个版本已经包含了所有平台的so了。
