### ISSUE TITLE
 [demo]:AtlasDemo Error:Execution failed for task ':app:transformDexWithInstantRunDependenciesApkForDebug'.

### ISSUE THREAD

**Issue by superfan** [alibaba/atlas#57]
最新的AtlasDemo build时出现
Error:Execution failed for task ':app:transformDexWithInstantRunDependenciesApkForDebug'.
> error
怎么解决？

**Comment by jinkailong** [comment]
Information:Gradle tasks [:app:assembleDebug]
Error:Execution failed for task ':app:transformDexWithInstantRunDependenciesApkForDebug'.
> error
Information:BUILD FAILED
Information:Total time: 1 mins 7.873 secs
Information:1 error
Information:0 warnings
Information:See complete output in console



我今天运行新的demo也是出现这个错误··

**Comment by zjutyujf** [comment]
instantrun 先关掉
