### ISSUE TITLE
[demo]新demo的firstbundle和secondbundle貌似没什么用啊

### ISSUE THREAD

**Issue by wuuchao** [alibaba/atlas#60]
mac
最终更新的还是FirstBundle，那新增的那两个library到底是干啥的
能不能再gradle.build里面注释一下各个配置是干嘛用的，就算demo跑起来还是一头雾水

**Comment by zjutyujf** [comment]
demo进去第一个tab的Activity就是来自于firstbundle的，第二个是secondbundle的，请先通过代码阅读下，时间比较紧，我们在补，谢谢
