### ISSUE TITLE
[demo]:update.json问题，"version":"1.0.0@unspecified"

### ISSUE THREAD

**Issue by renyihui** [alibaba/atlas#62]
{
	"baseVersion":"1.0.0",
	"updateBundles":[
		{
			"dependency":[],
			"isMainDex":false,
			"name":"com.taobao.firstbundle",
			"version":"1.0.0@unspecified"
		},
		{
			"isMainDex":true,
			"name":"com.taobao.maindex",
			"version":"1.0.0@1.0.1"
		}
	],
	"updateVersion":"1.0.1"
}
这个版本为什么是unspecified啊，而且在dependencyTree-debug.json文件中

"awbs":{
		"AtlasDemo:remotebundle:unspecified@awb":[],
		"AtlasDemo:publicbundle:unspecified@awb":[],
		"AtlasDemo:firstbundle:unspecified@awb":[],
		"AtlasDemo:secondbundle:unspecified@awb":[
			"AtlasDemo:secondbundlelibrary:unspecified@aar"
		]
	}
这个也是unspecified的，
动态部署的时候都不成功

**Comment by zjutyujf** [comment]
unspecified没有问题，因为工程依赖没有版本的概念，不成功的原因是什么？发出来下，可以加到首页里面给出二维码的钉钉群里面讨论
