### ISSUE TITLE
Release 开启混淆后，apk不能正常运行

### ISSUE THREAD

**Issue by ouyangjiwq** [alibaba/atlas#65]
1. demo问题的issue格式： [demo]:title

   使用Release, 开启混淆后，apk不能正常运行.报错
     
2. 容器功能接入或者如何使用的答疑：[use]:title
3. 提新需求的格式：[feature]:title

**Comment by zjutyujf** [comment]
请先把atlas容器的packagekeep下，我们稍后跟进下增加proguard keep
