### ISSUE TITLE
[use]customer aapt 不支持 -c 命令参数  windows平台下导致打补丁包失败

### ISSUE THREAD

**Issue by johnx4** [alibaba/atlas#66]
例如如下配置就会报错
aaptOptions {
     additionalParameters '-c', 'zh-rCN'
     additionalParameters "--no-version-vectors"
    }

**Comment by jiqimaogou** [comment]
additionalParameters "--no-version-vectors"
可以先把这个参数去掉，内部已经默认使用了。

**Comment by johnx4** [comment]
导致报错应该是这一行   additionalParameters '-c', 'zh-rCN'

**Comment by leafseelight** [comment]
可否发一份你编译好的aapt给我，ye.jg@qq.com

**Comment by hwjump** [comment]
新版已经修复
