### ISSUE TITLE
[demo]:新建bundle，参照sencondbundle的所有配置，依然无法在宿主APP中启动

### ISSUE THREAD

**Issue by hongxialiu** [alibaba/atlas#67]
有点小白，，但是我看代码和文档说明，实在没有看到在什么地方配置的。如果是路由的话，总会有个配置文件的吧。map.put(key,value).不然怎么就可以根据key找到activity。我没有找到，什么地方去配置新的bundlename。
列如：  switchToActivity("third","com.taobao.thirdbundle.MainActivity");这个的话，应该需要在什么地方把bundlename,"third"put进去吧。

**Comment by hwjump** [comment]
在打包阶段就会生成一个清单文件。包含所有bundle的activity和service信息。你可以参见 https://github.com/alibaba/atlas/blob/master/atlas-gradle-plugin/atlas-plugin/src/main/java/com/taobao/android/builder/tasks/app/prepare/PrepareBundleInfoTask.java 这个task。
然后atlas hook了系统startactivity的地方。通过你传的activity string来确定你是要起那个bundle里的activity。 所以不需要有配置文件，你只需要按照原生android的写法，写在AndroidManifest.xml里面即可。
