### ISSUE TITLE
[demo]:bundle中不能引用butterknife？

### ISSUE THREAD

**Issue by 317764920** [alibaba/atlas#69]
butterknife如何在所有bundle中使用

**Comment by jiawulu** [comment]
使用：

apply plugin: 'com.android.library'
apply plugin: 'com.taobao.atlas'

这种方式，按道理和butterknife 不冲突的

**Comment by 317764920** [comment]
@jiawulu 编译可以通过，能运行，但就是绑定没有成功


这是bundle的gradle配置：
apply plugin: 'com.android.library'
apply plugin: 'com.taobao.atlas'
apply plugin: 'com.jakewharton.butterknife'
apply plugin: 'com.neenbedankt.android-apt'

atlas {
    bundleConfig {
        awbBundle true
    }
    buildTypes {
        debug {
            baseApFile project.rootProject.file('app/build/outputs/apk/app-debug.ap')
        }
    }
}

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    providedCompile 'com.jakewharton:butterknife:8.5.1'
    apt 'com.jakewharton:butterknife-compiler:8.5.1'
    //6.0权限适配
    providedCompile 'com.zhy:mpermission-api:1.0.0'
    apt 'com.zhy:mpermission-compiler:1.0.0'
    providedCompile project(':lib.style')
    testCompile 'junit:junit:4.12'
}

**Comment by WeaponZhi** [comment]
butterKnife这个问题怎么解决的？
