### ISSUE TITLE
异步拉起Bundle有可能造成WindowLeaked

### ISSUE THREAD

**Issue by shubowen** [alibaba/atlas#73]
Intent intent = new Intent();
intent.setClassName(getBaseContext(),"com.taobao.demo.MainActivity");
startActivity(intent);
finish();

如果com.taobao.demo.MainActivity是在一个没有拉起的Bundle里，会走InstrumentationHook的asyncStartActivity，这里会创建加载的对话框，但是对话框会在finish()调用的时候造成WindowLeaked

**Comment by zjutyujf** [comment]
好的 这个我们这边跟进解决下

**Comment by walker0402** [comment]
请问下这个bug修复了么，我导入的demo按照Tpatch的步骤，push完两个文件到手机之后，点击demo的动态部署，重启app之后就会出现这个WindowLeaked的bug

**Comment by hwjump** [comment]
已修复
