### ISSUE TITLE
[demo]Execution failed for task ':app:packageDebugAwbs'

### ISSUE THREAD

**Issue by renyihui** [alibaba/atlas#74]
![image](https://cloud.githubusercontent.com/assets/26564557/24340361/29298174-12e4-11e7-9d96-cded9a8c1b05.png)
我们的项目集成后，执行gradlew clean assembleDebug老是报这个错误
但是直接运行就不会

**Comment by jiawulu** [comment]
更新最新的插件版本  2.3.0.alpha8 ， 已经修复
