### ISSUE TITLE
Bundle配置疑问

### ISSUE THREAD

**Issue by maolubin** [alibaba/atlas#75]
apply plugin: 'com.taobao.atlas'    这个有的Bundle有，有的没有，什么情况才需要设置呢

**Comment by hwjump** [comment]
当你要打awb 以及整包的时候要配置。  
以前我们是放在一个plugin里面，所以你会看到apply plugin: 'com.taobao.atlas.library' ，它其实是apply plugin: 'com.taobao.library' 和 apply plugin: 'com.taobao.atlas' 的结合体。  因为遇到有些插件会检查apply plugin: 'com.taobao.library' 有没有写
