### ISSUE TITLE
问一个仓库的问题  mavenLocal()是指哪个仓库?

### ISSUE THREAD

**Issue by WhySRZ** [alibaba/atlas#77]
字面上看是本地仓库   问题是怎么来的?readme中"如何构建一个APK，发布到各个应用市场"时也说了

"然后再在app目录下面执行../gradlew clean assembleDebug publish命令从而进行APK打包，生成的APK文件目录是app/build/outputs/apk/app-debug.apk，上述命令也会将该目录下的ap文件发布到**# 仓库**以便于后续生成patch。"

那么这里的仓库又是哪里呢?
是自己建的仓库么?maven仓库?怎么把Demo关联上呢?求赐教

**Comment by WhySRZ** [comment]
好吧知道mavenLocal()是什么了,做动画用的   剩下一个一个ap文件发的仓库是哪个仓库啊?还是不明白
如果自己要搭类似Demo的框架该从哪里开始着手?有大神指点下思路么?

**Comment by zjutyujf** [comment]
mavenlocal就是maven本地仓库
