### ISSUE TITLE
Android plugin不能使用支持instant run 

### ISSUE THREAD

**Issue by albert1017** [alibaba/atlas#8]
一但升级gradle和Android插件到支持Instant run版就无法编译通过

**Comment by zjutyujf** [comment]
是的，目前版本不支持instant run,需要关闭android studio中的instant run，目前支持awo的方式针对单模块编译测试（文档会及时更新），兼容instant run的快速编译正在开发中

**Comment by greeniecoder** [comment]
i think instant run is a essential feature in application development.
when a public library module changed,will feel really upset without instant run!!
