### ISSUE TITLE
[use]:Error:Execution failed for task ':app:packageDebugAwbs' 运行报错

### ISSUE THREAD

**Issue by 281884702** [alibaba/atlas#81]
自己写的demo,firstbundle中build awbbundle设置为true 运行就会报标题上的错误,,,,,, 用的是atlasplugin:2.3.0.alpha8   怎么解决?

**Comment by iwenchao** [comment]
请问在哪可以看如何解决？

**Comment by hwjump** [comment]
升级新的打包插件版本

**Comment by iwenchao** [comment]
ok，谢谢回复！

2017年6月20日 09:46，"hwjump" <notifications@github.com>写道：
