### ISSUE TITLE
[use]:能不能实现xml布局文件的更新

### ISSUE THREAD

**Issue by 317764920** [alibaba/atlas#82]
比如：
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context="com.cqxiaokang.main.MainActivity">

    <TextView
        android:id="@+id/tv_main_content"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:gravity="center"
        android:text="我是首页" />

    <Button
        android:id="@+id/btn_main_go"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="下一步" />

</LinearLayout>

改为
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context="com.cqxiaokang.main.MainActivity">

    <ImageView
        android:id="@+id/iv_main"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:src="@drawable/new_main" />

    <TextView
        android:id="@+id/tv_main_content"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:gravity="center"
        android:text="我是首页的新内容" />

    <Button
        android:id="@+id/btn_main_go"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="下一步" />

</LinearLayout>

我试了一下好像是不可以

**Comment by zjutyujf** [comment]
这个肯定是可以的，你是通过动态部署测试的么，可以看看readme的测试步骤

**Comment by 317764920** [comment]
@zjutyujf 是动态部署，patch也是生成成功的，代码上可以修改是ok，但是xml没有变化，不知道是不是我哪里配置错了

**Comment by maolubin** [comment]
我也是，我更新加了按钮，提示我这个按钮控件空指针

**Comment by 317764920** [comment]
@zjutyujf 确实是不能实现，用了你们提供的demo试了，还是不能更新，不会报错，但是新增的控件没有

**Comment by zjutyujf** [comment]
请加钉钉群讨论，这边重新测试了都没有问题
