### ISSUE TITLE
动态部署限制

### ISSUE THREAD

**Issue by maolubin** [alibaba/atlas#84]
这是官网的，
AndroidManifest保持不变

新增Activity的功能暂时关闭（下个大版本开放） 所以新增Activity，service等如果有需求在大版本里面先预留解决，如果要修改theme 通过代码设置来解决;receiver可以先考虑采用动态注册的方式

window级别使用的资源保持不变 Activity切换的动画文件、通知栏使用的logo等如果修改了也不会生效，不过不会产生问题，使用的还是原来的样式

还有我今天试了下，xml布局改了，也没生效，还有哪些不能更新的呢，能列一下吗

**Comment by zjutyujf** [comment]
xml布局是肯定可以修改的，新增Activity，service也马上会支持，不成功请贴一下出错的原因，或者根据首页钉钉群的二维码加入沟通一下
