### ISSUE TITLE
适配android O问题：atlas.init中对gDefault对象没有赋值。

### ISSUE THREAD

**Issue by juefei** [alibaba/atlas#87]
请按照下面的规则提交您的issue，符合标准的issue会被优先处理,
请先查看有没有同类型的issue已经存在.

1. demo问题的issue格式： [demo]:title

   title尽量反应问题的状况，如果是编译问题或者无法运行，正文写明是windows还是mac，如果是不清楚如何使用demo，请先查看https://github.com/alibaba/atlas/blob/master/atlas-demo/README.zh_cn.md
     
2. 容器功能接入或者如何使用的答疑：[use]:title
3. 提新需求的格式：[feature]:title

**Comment by zjutyujf** [comment]
已经修改，非常感谢
