### ISSUE TITLE
集成百度定位SDK v7.1后，生成的apk中没有dex

### ISSUE THREAD

**Issue by superfan** [alibaba/atlas#89]
请问，在主程序（不是bundle）中集成了百度定位SDK v7.1，可以编译出apk（没有报错），但是里面没有dex，这个要怎么解决？

**Comment by jiawulu** [comment]
百度 定位 sdk 的 依赖 贴出来， 我们本地调一下

**Comment by superfan** [comment]
1、导入库文件
百度库文件，jar和so

2、在build.gradle添加
sourceSets {
        main {
    		jniLibs.srcDirs = ['libs']
        }
}

3、在AndroidManifest.xml添加service、权限和AcessKey

4、调用相应的api，可以编译成功。

具体参考：
http://lbsyun.baidu.com/index.php?title=android-locsdk/guide/buildprojec

**Comment by jiawulu** [comment]
https://github.com/hiAndroid/atlasforbaiduloc

本地测试没什么问题，我直接在 baidu 的demo工程上改的：

1. 升级 插件 到 2.3
2. 添加atlas插件


![image](https://cloud.githubusercontent.com/assets/748188/24574985/ae4f48a6-16cd-11e7-9972-71af6101a212.png)
