### ISSUE TITLE
用Atlas搭建的框架,没有办法使用ARouter么?

### ISSUE THREAD

**Issue by WhySRZ** [alibaba/atlas#91]
https://github.com/alibaba/ARouter,想使用路由更好传递数据,可是集成后没办法在Atlas下实现跳转.到底是为什么呢?难道一定要用包名加类名实现跳转么?

**Comment by hwjump** [comment]
不支持。 不过我觉得你可以为atlas写个ARouter插件。就是在ARouter跳转的时候，做一个适配，提前解析出包名类名，再塞给atlas跳转

**Comment by caijixia** [comment]
问下群主，atlas适配arouter的方案有进展吗？

**Comment by hwjump** [comment]
atlas本身没有， 不过有网友改过ARouter  https://github.com/JiangDaYa0/ARouter   你可以研究下
