### ISSUE TITLE
bundle中自定义了application类

### ISSUE THREAD

**Issue by superfan** [alibaba/atlas#93]
请问大神，我在bundle中自定义了application类，其中的自定义方法怎么在bundle中调用？
在bundle中调用getApplication方法，得到的是主应用的application对象，不是bundle中定义的。

**Comment by hwjump** [comment]
首先要确定一点，bundle中的application不是最终在android系统上执行的application。我们之所以保留application的设计是为了尽最大可能保留大家android的开发习惯。
所以大家在bundle中的application，不要使用this这种用bundle application的代码，因为是不生效的。
bundle中的application类的自定义方法，我们建议不要这么使用。可以抽离出公共的方法，放在其他地方供调用。  目前是有这个限制。
