### ISSUE TITLE
bundle中集成dagger、butterknife后，生成的apk中没有bundle对应的so

### ISSUE THREAD

**Issue by superfan** [alibaba/atlas#98]
demo代码
https://github.com/superfan/TestAtlas

**Comment by hwjump** [comment]
这个问题我们研究下

**Comment by jiawulu** [comment]
@superfan https://github.com/hiAndroid/butterknifeForAtlas ,

根据你的demo改了2点：

1. 全局排除了butterknife
2. app 里增加了修改后的 butterknife

**Comment by superfan** [comment]
可以了，但是butterknife-debug.aar如何编译出来？

**Comment by jiawulu** [comment]
@superfan 你可以看下官方仓库的变更，已经提交pr了，
